package rules.Assignment.DefaultGroupActivityAssignmentRules_dir

@gw.rules.RuleName("DGAAIM100 - PIM Default Group Activity Assignment Rules")
internal class DGAAIM100PIMDefaultGroupActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
