package rules.Assignment.DefaultGroupActivityAssignmentRules_dir

@gw.rules.RuleName("DGAAXX100 - All BUs Default Group Activity Assignment Rules")
internal class DGAAXX100AllBUsDefaultGroupActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
