package rules.Validation.MatterValidationRules_dir.MVXX1000AllBUsMatterValidationRules_dir

@gw.rules.RuleName("MVXX1100 - Dates Requirements")
internal class MVXX1100DatesRequirements {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
