package rules.Preupdate.PolicyPreupdate_dir.PPUXXPOSTRulesonlyapplicableafterNCW_dir

@gw.rules.RuleName("PPUEQ1000 - Equine Policy PreUpdate Rules")
internal class PPUEQ1000EquinePolicyPreUpdateRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
