package rules.Preupdate.MatterAssignmentExtPreupdate_dir.MAPUXX1000AllBUsPreUpdateRules_dir

@gw.rules.RuleName("MAPUXX1400 - Generate Activities From LitAdvisor Updates")
internal class MAPUXX1400GenerateActivitiesFromLitAdvisorUpdates {
  static function doCondition(matterAssignmentExt : entity.MatterAssignmentExt) : boolean {
    return /*start00rule*/!matterAssignmentExt.New &&
(matterAssignmentExt.ChangedFields.contains("BudgetExt")||
matterAssignmentExt.ChangedFields.contains("StaffingPlanExt")||
matterAssignmentExt.ChangedFields.contains("StaffBudgetRequiredExt"))

/*end00rule*/
  }

  static function doAction(matterAssignmentExt : entity.MatterAssignmentExt, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
