package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPU04000 - Reinsurance")
internal class TPU04000Reinsurance {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/TransactionSet.Claim.ReinsuranceReportable == null/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
