package rules.Assignment.DefaultGroupExposureAssignmentRules_dir

@gw.rules.RuleName("DGEAIM100 - PIM Default Group Exposure Assignment Rules")
internal class DGEAIM100PIMDefaultGroupExposureAssignmentRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
