package rules.Assignment.DefaultGroupExposureAssignmentRules_dir

@gw.rules.RuleName("DGEAXX100 - All BUs Default Group Exposure Assignment Rules")
internal class DGEAXX100AllBUsDefaultGroupExposureAssignmentRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
