package rules.Preupdate.TransactionSetPreupdate_dir.TPUXX1000AllBUTransactionPreUpdate_dir.TPUXX1200CheckSet_dir.TPUXX12C0LitAdvisorChecks_dir

@gw.rules.RuleName("TPUXX12C1 - Set Check Payee Role")
internal class TPUXX12C1SetCheckPayeeRole {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/(transactionSet as CheckSet).Changed == true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/var payee = (transactionSet as CheckSet).PrimaryCheck.Payees[0].ClaimContact.Contact;
(transactionSet as CheckSet).Claim.addRole(ContactRole.TC_CHECKPAYEE, payee)/*end00rule*/
  }
}
