package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1100NewLossFieldRequirements_dir.EVXX1120CoverageRequirements_dir

@gw.rules.RuleName("EVXX1122 - Coverage Subtype Required")
internal class EVXX1122CoverageSubtypeRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*Requires Coverage Subtype at the new loss level.
  Sprint/Maintenance Release: Sprint 16
  Author: Zach Thomas
  Date: 9/30/08
*/
exposure.CoverageSubType == null and !exposure.ReconnectFailExt/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  if(exposure.CoverageSubType == null and !exposure.ReconnectFailExt){
    exposure.rejectField( "CoverageSubType", "newloss", displaykey.Rules.Validation.Exposure.Enterprise.Exposure.CoverageSubtype, null, null );
  }
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( exposure, actions.getRule() as java.lang.String, e, null )
}  /*end00rule*/
  }
}
