package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1100ValidationattheISOLevel_dir

@gw.rules.RuleName("CVXX1110 - Loss Cause is Required")
internal class CVXX1110LossCauseisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossCause == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "LossCause", "iso", "Loss Cause is required.", Null, Null )/*end00rule*/
  }
}
