package rules.Postsetup.ExposurePostsetup_dir

@gw.rules.RuleName("EPOEQ1000 - Equine Exposure PostSetup Rules")
internal class EPOEQ1000EquineExposurePostSetupRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
