package rules.Postsetup.ExposurePostsetup_dir

@gw.rules.RuleName("EPOIM1000 - PIM Exposure PostSetup Rules")
internal class EPOIM1000PIMExposurePostSetupRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
