package rules.Validation.MatterClosedValidationRules_dir

@gw.rules.RuleName("MCV01000 - Close Before Trial")
internal class MCV01000CloseBeforeTrial {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/Matter.TrialDate > gw.api.util.DateUtil.currentDate()/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/// This is a test rule, introduced to test validation warnings in close validation rules
Matter.reject( null, null, "loadsave", displaykey.Rules.Validation.CloseMatter.CloseBeforeTrialDate )/*end00rule*/
  }
}
