package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir.ECVXX1600MedicareRelated_dir.ECVXX1630MedicareEligibleFalse_dir

@gw.rules.RuleName("ECVXX1635 - Fill Out Stop Sending Indicator Warning")
internal class ECVXX1635FillOutStopSendingIndicatorWarning {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/(exposure.Claimant as Person).StopSendPartyToCMSExt == null
 
//Stephanie Przygocki EM26 - Stop Sending Flag must be flagged to the user to see
//if they mean to close the feature without populating./*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var strErrorReason = "If you do not want to continue the CMS query, update \"Stop Querying for CMS\" prior to closing this feature."
exposure.reject( null, null, "newloss", strErrorReason )/*end00rule*/
  }
}
