package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir

@gw.rules.RuleName("CVWC1300 - Validation at ISO Level")
internal class CVWC1300ValidationatISOLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
