package rules.Preupdate.ClaimPreupdate_dir.CPUWC1000WorkersCompClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUWC2100 - Add Former Role")
internal class CPUWC2100AddFormerRole {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
