package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVAG1000 - AgriBusiness Exposure Validation Rules")
internal class EVAG1000AgriBusinessExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType=="AGRIAUTO" ||
Exposure.Claim.LossType=="AGRILIABILITY" ||
Exposure.Claim.LossType=="AGRIPROPERTY"OR 
exposure.Claim.LossType==LossType.TC_ALTMARKETSAUTO 
OR exposure.Claim.LossType==LossType.TC_SHSAUTO
OR exposure.Claim.LossType==LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
