package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVCA1000 - Commercial Auto Exposure Validation Rules")
internal class EVCA1000CommercialAutoExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType==typekey.LossType.TC_AGRIAUTO or
exposure.Claim.LossType==typekey.LossType.TC_ALTMARKETSAUTO or
exposure.Claim.LossType==typekey.LossType.TC_SHSAUTO or
exposure.Claim.LossType==typekey.LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
