package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVELD1000 - ELD Exposure Validation Rules")
internal class EVELD1000ELDExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == "EXECLIABDIV" || exposure.Claim.LossType == LossType.TC_MERGACQU || exposure.Claim.LossType == LossType.TC_SPECIALHUMSERV/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
