package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVEQ1000 - Equine Exposure Validation Rules")
internal class EVEQ1000EquineExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType=="EQUINE" /*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
