package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVIM1000 - PIM Exposure Validation Rules")
internal class EVIM1000PIMExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
