package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVISO000 - ISO Exposure Validation Rules")
internal class EVISO000ISOExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.ISOEnabled==true or
exposure.Claim.LossType==typekey.LossType.TC_EXCESSLIABILITY or 
exposure.Claim.LossType==typekey.LossType.TC_EXCESSLIABILITYAUTO or 
exposure.Claim.LossType==typekey.LossType.TC_SPECIALTYES or
exposure.Claim.LossType==typekey.LossType.TC_MERGACQU/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
