package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVPA1000 - Personal Auto Exposure Validation Rules")
internal class EVPA1000PersonalAutoExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType=="PERSONALAUTO"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
