package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVWC1000 - Workers Comp Exposure Validation Rules")
internal class EVWC1000WorkersCompExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(exposure.Claim)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
