package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EVXX1000 - ALL BUs Exposure Validation Rules")
internal class EVXX1000ALLBUsExposureValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
