package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO500 - Boat Payload")
internal class EVISO500BoatPayload {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.getISOPayloadType() == "Boat"
and ((exposure.Coverage as VehicleCoverage).RiskUnit as VehicleRU).Vehicle!=null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
