package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO100 - General Requirements")
internal class EVISO100GeneralRequirements {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ReconnectFailExt != true and exposure.Claim.Policy.isPolicyInRefresh( 0 )/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
