package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO300 - Injury (Casualty) Payload")
internal class EVISO300InjuryCasualtyPayload {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///Casualty (injury) claims are all injury, libel (etc) or 
//3rd party property claims
exposure.getISOPayloadType() == "Injury"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
