package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO200 - Party Information")
internal class EVISO200PartyInformation {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
