package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO600 - Property Payload")
internal class EVISO600PropertyPayload {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///There are no required fields for Property Payload

//Requested fields are:
//  -Policy Section (identifies coverage)
//  -Dollar amount for one of: Insurance/Policy Amount, 
//          Estimated Loss Amount, Loss Reserve or Settlement Amount

//ISO XML Manual v.5 page 35-36
exposure.getISOPayloadType() == "Property"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
