package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir

@gw.rules.RuleName("EVISO700 - Type of Loss Required")
internal class EVISO700TypeofLossRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType==typekey.LossType.TC_ENVLIAB/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var reason:String = displaykey.Rules.Validation.Exposure.Environmental.SendToISO

if(exposure.TypeOfLossMostExt==null){
  exposure.reject(typekey.ValidationLevel.TC_ISO, exposure + ": " + reason, null, null)
}/*end00rule*/
  }
}
