package rules.InitialReserve.InitialReserve_dir.IRR01000Auto_dir.IRR01100Vehicledamage_dir

@gw.rules.RuleName("IRR01130 - AutoFirstAndFinal")
internal class IRR01130AutoFirstAndFinal {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
