package rules.Preupdate.ClaimPreupdate_dir.CPUEN1000EnvironmentalClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUEN1100 - Set Medicare Flag")
internal class CPUEN1100SetMedicareFlag {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for (exp in claim.Exposures){
  exp.MedicareExposureExt = exp.isMedicareFeature(exp)
}/*end00rule*/
  }
}
