package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

@gw.rules.RuleName("EXV05100 - Not Draft")
internal class EXV05100NotDraft {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.State == "draft"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField( "State", "iso", displaykey.Rules.Validation.Exposure.MustNotBeDraft, null, null )/*end00rule*/
  }
}
