package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

@gw.rules.RuleName("EXV05300 - Coverage Subtype")
internal class EXV05300CoverageSubtype {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.CoverageSubType == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField( "CoverageSubType", "iso", displaykey.Rules.Validation.Exposure.CoverageSubTypeNotNull, null, null )/*end00rule*/
  }
}
