package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir

@gw.rules.RuleName("EXV05200 - Primary Coverage")
internal class EXV05200PrimaryCoverage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.PrimaryCoverage == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField( "PrimaryCoverage", "iso", displaykey.Rules.Validation.Exposure.CoverageNotNull, null, null )
/*end00rule*/
  }
}
