package rules.Preupdate.ExposurePreupdate_dir.EPUWC1000WorkersCompExposurePreUpdateRules_dir

@gw.rules.RuleName("EPUWC1300 -Add Former Role")
internal class EPUWC1300AddFormerRole {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
