package rules.Preupdate.ClaimPreupdate_dir.CPUBS1000BondsPreUpdateRules_dir

@gw.rules.RuleName("CPUBS1100 - RULES THAT CREATE ACTIVITIES")
internal class CPUBS1100RULESTHATCREATEACTIVITIES {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
