package rules.Postsetup.ExposurePostsetup_dir.EPOEQ1000EquineExposurePostSetupRules_dir

@gw.rules.RuleName("EPOEQ1100 - Set New Incident")
internal class EPOEQ1100SetNewIncident {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.New/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.setEquineIncident(exposure.returnProperty())/*end00rule*/
  }
}
