package rules.Workplan.ClaimWorkplan_dir.CLW03000Newusers_dir

@gw.rules.RuleName("CLW03100 - Verify coverage")
internal class CLW03100Verifycoverage {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.createActivityFromPattern(null, ActivityPattern.finder.getActivityPatternByCode("coverage"))/*end00rule*/
  }
}
