package rules.Assignment.GlobalMatterAssignmentRules_dir

@gw.rules.RuleName("GMAEQ100 - Equine Global Matter Assignment Rules")
internal class GMAEQ100EquineGlobalMatterAssignmentRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
