package rules.Assignment.GlobalMatterAssignmentRules_dir

@gw.rules.RuleName("GMAIM100 - PIM Global Matter Assignment Rules")
internal class GMAIM100PIMGlobalMatterAssignmentRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
