package rules.Assignment.GlobalMatterAssignmentRules_dir

@gw.rules.RuleName("GMAXX100 - All BU Global Matter Assignment Rules")
internal class GMAXX100AllBUGlobalMatterAssignmentRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
