package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW02000 - Thirty day review")
internal class CLW02000Thirtydayreview {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.createActivityFromPattern(null, ActivityPattern.finder.getActivityPatternByCode("initial_30day_review"))/*end00rule*/
  }
}
