package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW04000 - Auto claims")
internal class CLW04000Autoclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AUTO" and not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
