package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW05000 - Property claims")
internal class CLW05000Propertyclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "PR" and not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
