package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW03000 - New users")
internal class CLW03000Newusers {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignedUser.ExperienceLevel == "low" and not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
