package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW06000 - Liablity claims")
internal class CLW06000Liablityclaims {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "GL" and not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
