package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CLW01000 - Contact insured")
internal class CLW01000Contactinsured {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/not claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.createActivityFromPattern(null, ActivityPattern.finder.getActivityPatternByCode("contact_insured"))/*end00rule*/
  }
}
