package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("EFR04000 - Console")
internal class EFR04000Console {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/MessageContext.DestID == 68/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/MessageContext.createMessage( displaykey.Rules.EventFired(MessageContext.EventName))/*end00rule*/
  }
}
