package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVXX3000-Open Recovery Estimates")
internal class ECVXX3000OpenRecoveryEstimates {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if(exposure.getFeatureFinancialReserveRecoveryStatus()=="Open"){
exposure.reject( "newloss","This Feature will not be closed with open Recovery Estimates.",null,null)
}/*end00rule*/
  }
}
