package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVXX1300 - Pending Assignment - Exposure")
internal class ECVXX1300PendingAssignmentExposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.AssignmentStatus == "pendingassignment" or
exposure.AssignmentStatus == "unassigned" or
exposure.AssignmentStatus == "manual"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "newloss", "You cannot close feature (" + exposure.DisplayName + ") on claim (" + exposure.Claim.ClaimNumber + ") while in Pending Assignment Status. Please assign the feature and then close.", null, null )/*end00rule*/
  }
}
