package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVXX1600 - Medicare Related")
internal class ECVXX1600MedicareRelated {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.gaic.CMS.validation.CMSValidationUtil.generalPrecondition(exposure)
and !exposure.claim.Policy.isPolicyInRefresh( 1 )

  /**
   * Conditions that must be true:
   *   1) Medicare Type exposure
   *   2) Claimant exactly of type Person (not PersonVendor) or InjuredWorkerExt
   *     11.10.15 - cmullin - Claimant must be Person or InjuredWorkerExt (new for WC)
   *//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
