package rules.ApprovalRouting.BulkInvoiceApprovalAssignmentRules_dir

@gw.rules.RuleName("BIAR1000 - Bulk Invoice Approval Routing Rules")
internal class BIAR1000BulkInvoiceApprovalRoutingRules {
  static function doCondition(bulkInvoice : entity.BulkInvoice) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(bulkInvoice : entity.BulkInvoice, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
