package rules.Preupdate.PolicyPreupdate_dir

@gw.rules.RuleName("PPUXXPOST - Rules only applicable after NCW")
internal class PPUXXPOSTRulesonlyapplicableafterNCW {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.State != "draft"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
