package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05500NonWorkersComp_dir

@gw.rules.RuleName("EXV05510 - Claimant Exists")
internal class EXV05510ClaimantExists {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ClaimantDenorm == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField( "Claimant", "iso", displaykey.Rules.Validation.Exposure.ClaimantNotNull, null, null )/*end00rule*/
  }
}
