package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05500NonWorkersComp_dir

@gw.rules.RuleName("EXV05520 - Name")
internal class EXV05520Name {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ClaimantDenorm != null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if( exposure.ClaimantDenorm typeis Person )
{
  var person = exposure.ClaimantDenorm
  if( person.FirstName == null || person.FirstName.length() == 0 )
  {
    exposure.rejectSubField( person, "FirstName", "iso", displaykey.Rules.Validation.Exposure.ClaimantFirstNameNotNull, null, null )
  }
  if( person.LastName == null || person.LastName.length() == 0 )
  {
    exposure.rejectSubField( person, "LastName", "iso", displaykey.Rules.Validation.Exposure.ClaimantLastNameNotNull, null, null )
}
}
else if( exposure.ClaimantDenorm typeis Company )
{
  var company = exposure.ClaimantDenorm
  if( company.Name == null || company.Name.length() == 0 )
  {
    exposure.rejectSubField( company, "Name", "iso", displaykey.Rules.Validation.Exposure.ClaimantCompanyNameNotNull, null, null )
  }
}/*end00rule*/
  }
}
