package rules.Validation.ClaimValidationRules_dir.CVIM1000PIMClaimValidationRules_dir.CVIM1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVIM1110 - Level of Reserve required")
internal class CVIM1110LevelofReserverequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LevelOfReserveExt==null and claim.Exposures.length!=0/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try{
  claim.rejectField("LevelOfReserveExt", "newloss", displaykey.Rules.Validation.Claim.PIM.LevelOfReserve, null, null)
  } catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( Exposure, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
