package rules.Validation.PolicyValidationRules_dir

@gw.rules.RuleName("PV - NonVerified Only")
internal class PVNonVerifiedOnly {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.State != "draft" or !policy.Verified/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
