package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVAC1000 - Commercial Auto Validation Rules")
internal class CVAC1000CommercialAutoValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType==LossType.TC_AGRIAUTO or 
claim.LossType==LossType.TC_ALTMARKETSAUTO or 
claim.LossType==LossType.TC_SHSAUTO or 
claim.LossType==LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
