package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVAG1000 - Agribusiness Claim Validation Rules")
internal class CVAG1000AgribusinessClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_AGRIAUTO  or
claim.LossType == LossType.TC_AGRILIABILITY or
claim.LossType == LossType.TC_AGRIPROPERTY 
/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
