package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVAV1000 - Aviation Claim Validation Rules")
internal class CVAV1000AviationClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_AVIATION/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
