package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVEL1000 - Executive Liability Claim Validation Rules")
internal class CVEL1000ExecutiveLiabilityClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "EXECLIABDIV" || claim.LossType == LossType.TC_MERGACQU || claim.LossType == LossType.TC_SPECIALHUMSERV/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
