package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVEQ1000 - Equine Claim Validation Rules")
internal class CVEQ1000EquineClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
