package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVFC1000 - FidCrime Claim Validation Rules")
internal class CVFC1000FidCrimeClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="FIDCRIME" or
claim.LossType=="KIDNAPRANSOM"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
