package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVIM1000 - PIM Claim Validation Rules")
internal class CVIM1000PIMClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
