package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVPL1000 - Professional Liability Claim Validation Rules")
internal class CVPL1000ProfessionalLiabilityClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossType == "PROFLIABDIV"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
