package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVSP1000 - Specialty E&S Claim Validation Rules")
internal class CVSP1000SpecialtyESClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
