package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVWC1000 - Workers' Comp Claim Validation Rules")
internal class CVWC1000WorkersCompClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
