package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CVXX1000 - All Business Unit Claim Validation Rules")
internal class CVXX1000AllBusinessUnitClaimValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
