package rules.Validation.ClaimValidationRules_dir.CVIM1000PIMClaimValidationRules_dir

@gw.rules.RuleName("CVIM1300 - Validation at Ability to Pay Level")
internal class CVIM1300ValidationatAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
