package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVWC1000WorkersCompPolicyValidationRules_dir

@gw.rules.RuleName("PVWC1200 - Ability To Pay")
internal class PVWC1200AbilityToPay {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
