package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05740Boat_dir

@gw.rules.RuleName("EXV05741 - HIN Present")
internal class EXV05741HINPresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.LossParty != "third_party" 
and exposure.VehicleIncident.Vehicle.Year != null
and exposure.VehicleIncident.Vehicle.Year >= gw.api.iso.ISOValidationConstants.YEAR_HIN_REQUIRED
and exposure.VehicleIncident.Vehicle.SerialNumber == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.BoatHINRequired, null, null);/*end00rule*/
  }
}
