package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05740Boat_dir

@gw.rules.RuleName("EXV05743 - Boat Type Present")
internal class EXV05743BoatTypePresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.VehicleIncident.Vehicle.BoatType == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.BoatTypeRequired, null, null);/*end00rule*/
  }
}
