package rules.Preupdate.ExposurePreupdate_dir.EPUIM1000PIMExposurePreUpdateRules_dir

@gw.rules.RuleName("EPUIM11200 - Motor Truck Coverage")
internal class EPUIM11200MotorTruckCoverage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == ExposureType.TC_IM_MOTORTRUCKCARGO/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
