package rules.Validation.PolicyValidationRules_dir

@gw.rules.RuleName("POV02000 - Original Effective Date")
internal class POV02000OriginalEffectiveDate {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/Policy.OrigEffectiveDate != null &&
    Policy.OrigEffectiveDate > Policy.EffectiveDate/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/Policy.rejectField( "EffectiveDate",
                    "newloss",
                    displaykey.Rules.Validation.Policy.PolicyEffectiveDateLaterThanOriginalEffectiveDate,
                    null,
                    null )/*end00rule*/
  }
}
