package rules.Validation.PolicyValidationRules_dir

@gw.rules.RuleName("POV01000 - Effective and Expiration Dates")
internal class POV01000EffectiveandExpirationDates {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/Policy.EffectiveDate > Policy.ExpirationDate/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/Policy.rejectField( "EffectiveDate",
                    "newloss",
                    displaykey.Rules.Validation.Policy.PolicyExpirationLaterThanEffectiveDate,
                    null,
                    null )/*end00rule*/
  }
}
