package rules.Validation.PolicyValidationRules_dir

@gw.rules.RuleName("POV03000 - Endorsement Dates")
internal class POV03000EndorsementDates {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/for (e in Policy.Endorsements) {
  if ((e.EffectiveDate != null) &&
      (e.ExpirationDate != null) &&
      (e.EffectiveDate > e.ExpirationDate)) {
      Policy.reject( "newloss", displaykey.Rules.Validation.Policy.EndorsementExpirationLaterThanEffectiveDate, null, null )
  }
}/*end00rule*/
  }
}
