package rules.Reopened.MatterReopened_dir

@gw.rules.RuleName("MREQ1000 - Equine Matter Reopened Rules")
internal class MREQ1000EquineMatterReopenedRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
