package rules.Preupdate.ClaimPreupdate_dir.CPU16000Travel_dir

@gw.rules.RuleName("CPU16100 - Trip Incident")
internal class CPU16100TripIncident {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.TripIncidentsOnly.length > 0/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
