package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir

@gw.rules.RuleName("CEEN1000 - ENV Claim Exception Rules")
internal class CEEN1000ENVClaimExceptionRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "ENVLIAB"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
