package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir

@gw.rules.RuleName("CEEQ1000 - Equine Claim Exception Rules")
internal class CEEQ1000EquineClaimExceptionRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
