package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir

@gw.rules.RuleName("CEIM1000 - PIM Claim Exception Rules")
internal class CEIM1000PIMClaimExceptionRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
