package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir

@gw.rules.RuleName("CESP1000 - Specialty E&S Claim Exception Rules")
internal class CESP1000SpecialtyESClaimExceptionRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType ==  LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
