package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir

@gw.rules.RuleName("CEWC1000 - Workers' Comp Claim Exception Rules")
internal class CEWC1000WorkersCompClaimExceptionRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
