package rules.Assignment.DefaultGroupMatterAssignmentRules_dir

@gw.rules.RuleName("DGM01000 - Default")
internal class DGM01000Default {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/
matter.CurrentAssignment.assignUserByRoundRobin(false, matter.CurrentAssignment.AssignedGroup );/*end00rule*/
  }
}
