package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir

@gw.rules.RuleName("EVWC1200 - Ability to Pay Field Requirements")
internal class EVWC1200AbilitytoPayFieldRequirements {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
