package rules.Presetup.ExposurePresetup_dir

@gw.rules.RuleName("EPREQ1000 - Equine Exposure Pre Setup Rules")
internal class EPREQ1000EquineExposurePreSetupRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
