package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVXX11B0 - Line of Business Required")
internal class CVXX11B0LineofBusinessRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LOBCode==null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try{
  claim.reject( "newloss", "Claim must be associated with a line of business", null, null )
} catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
