package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVXX1150 - Loss Location State is Required")
internal class CVXX1150LossLocationStateisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*//*
This rule requires the user to enter a loss location state only if the country
is null or is inside the United States or Canada.
Author: Stephanie Przygocki
Date: 2-25-09
EM14 Defect Related: 1615
*/
//Claim.LossLocation.State==Null and 
//(Claim.LossLocation.Country=="US" || Claim.LossLocation.Country==null)

//MMANALILI 2010-02-21-- DEFECT 3846  The validation will no longer point to the
//Claim.LossLocation.State but instead will point to the Claim.LossLocation
//See defect 3846 for details.

claim.LossLocation== null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/var msg:String = "Enter the Loss Location State on the Loss Details Screen."

claim.rejectField( "LossLocation", "newloss", msg, Null, Null )/*end00rule*/
  }
}
