package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVXX1160 - Loss Type is Required")
internal class CVXX1160LossTypeisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == null  /*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "LossType", "newloss", "Loss type must not be left empty.", null, null )/*end00rule*/
  }
}
