package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVXX1180 - Claim Business Unit Required")
internal class CVXX1180ClaimBusinessUnitRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.custom_Ext.OfficeBranchFunctions.getClaimOfficeBranch(claim) == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "AssignedGroup", "newloss", "Branch office cannot be left blank.", null, null )/*end00rule*/
  }
}
