package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EXV07000 - Salvage")
internal class EXV07000Salvage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///Check for negative net recovery amounts
Exposure.VehicleIncident.SalvageProceeds - Exposure.VehicleIncident.SalvageTow - Exposure.VehicleIncident.SalvageStorage <= 0/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.reject( "newloss", displaykey.Rules.Validation.Exposure.SalvageRecoveryNotZeroOrNegative, null, null)/*end00rule*/
  }
}
