package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("EXV02000 - Other coverage but no info")
internal class EXV02000Othercoveragebutnoinfo {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.OtherCoverage and
 (Exposure.OtherCoverageDet.length == 0)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* This rule causes ClaimCenter to enforce that exposures
   fill in "other coverage" data during validation.
*/
Exposure.rejectField( "OtherCoverage",
  "newloss", displaykey.Rules.Validation.ProvideClaimantsOtherCoverage,
  null, null )/*end00rule*/
  }
}
