package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("EXV04000 - Coverage not null")
internal class EXV04000Coveragenotnull {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/// Use this rule to restrict user from writing a check for Workers' Comp. Exposures that have no appropriate coverage in the policy.
Exposure.Claim.Policy.PolicyType == "comp" and
Exposure.Coverage == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField( "Coverage", "payment", displaykey.Rules.Validation.Exposure.SpecifyCoverage, null, null )/*end00rule*/
  }
}
