package rules.Validation.ExposureValidationRules_dir

@gw.rules.RuleName("EXV01000 - Incident not null")
internal class EXV01000Incidentnotnull {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Incident == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.reject( "loadsave", displaykey.Rules.Validation.Exposure.NoIncident, null, null )/*end00rule*/
  }
}
