package rules.Preupdate.ClaimPreupdate_dir.CPUXX1000GlobalBuisnessPreUpdateRules_dir

@gw.rules.RuleName("CPUXX1AA0 - ISO")
internal class CPUXX1AA0ISO {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*///Uncommenting for now as this will go with EM23 - sprzygocki

claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
