package rules.Preupdate.ClaimPreupdate_dir.CPUXX1000GlobalBuisnessPreUpdateRules_dir

@gw.rules.RuleName("CPUXX1N00 - Claim on Policy Refresh")
internal class CPUXX1N00ClaimonPolicyRefresh {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Policy.isPolicyInRefresh( 1 )==true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.PolicyRefreshedExt = true/*end00rule*/
  }
}
