package rules.Validation.ClaimValidationRules_dir.CVEL1000ExecutiveLiabilityClaimValidationRules_dir

@gw.rules.RuleName("CVEL1400 - Validation at the ISO Level")
internal class CVEL1400ValidationattheISOLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*///Execute Children/*end00rule*/
  }
}
