package rules.Closed.MatterClosed_dir

@gw.rules.RuleName("MCEQ1000 - Equine Matter Closed Rules")
internal class MCEQ1000EquineMatterClosedRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
