package rules.ActivityGeneratorBatch.ConversionActivityGeneratorBatchRules_dir

@gw.rules.RuleName("CAXX1000 - All BU Conversion Activity Batch Rules")
internal class CAXX1000AllBUConversionActivityBatchRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
