package rules.InitialReserve.InitialReserve_dir.IRR01000Auto_dir

@gw.rules.RuleName("IRR01100 - Vehicle damage")
internal class IRR01100Vehicledamage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ExposureType=="vehicledamage"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
