package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVAG1000AgriBusinessPolicyValidationRules_dir.PVAG1300AbilitytoPay_dir

@gw.rules.RuleName("PVAG1320 - RULES FOR ISO AND ATP")
internal class PVAG1320RULESFORISOANDATP {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Claim.ISOEnabled/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
