package rules.Preupdate.ExposurePreupdate_dir.EPUXX1000AllBUExposurePreUpdateRules_dir

@gw.rules.RuleName("EXPUXX2200 - Medicare Exposures")
internal class EXPUXX2200MedicareExposures {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.MedicareExposureExt or exposure.IsMedicareExposureExt/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
