package rules.Validation.ExposureClosedValidationRules_dir.ECVAG1000AgribusinessExposureClosedValidationRules_dir.ECVAG1100TotalLossFieldsRequiredforISO_dir

@gw.rules.RuleName("ECVAG1130 - Is Owner Retaining Salvage? Required")
internal class ECVAG1130IsOwnerRetainingSalvageRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.VehicleIncident.IsOwnerRetainingExt == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("IsOwnerRetainingExt", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.IsOwnerRetainingSalvage, null, null);/*end00rule*/
  }
}
