package rules.Validation.ExposureClosedValidationRules_dir.ECVAG1000AgribusinessExposureClosedValidationRules_dir.ECVAG1100TotalLossFieldsRequiredforISO_dir

@gw.rules.RuleName("ECVAG1140 - Owner At Claim Close and Address Required")
internal class ECVAG1140OwnerAtClaimCloseandAddressRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.VehicleIncident.OwnLienAtClaimCloseExt == null || 
exposure.VehicleIncident.OwnLienAtClaimCloseExt.PrimaryAddress == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("OwnLienAtClaimCloseExt", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.AtConclusionOfClaim, null, null);/*end00rule*/
  }
}
