package rules.Validation.ExposureClosedValidationRules_dir.ECVAG1000AgribusinessExposureClosedValidationRules_dir.ECVAG1100TotalLossFieldsRequiredforISO_dir

@gw.rules.RuleName("ECVAG1120 - Owner At Accident and Address Required")
internal class ECVAG1120OwnerAtAccidentandAddressRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.VehicleIncident.OwnLienAtAccidentExt == null || 
exposure.VehicleIncident.OwnLienAtAccidentExt.PrimaryAddress == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("OwnLienAtAccidentExt", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.AtTimeOfAccident, null, null);/*end00rule*/
  }
}
