package rules.Validation.ExposureClosedValidationRules_dir.ECVAG1000AgribusinessExposureClosedValidationRules_dir.ECVAG1100TotalLossFieldsRequiredforISO_dir

@gw.rules.RuleName("ECVAG1150 - Vehicle Information Required")
internal class ECVAG1150VehicleInformationRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.VehicleIncident.Vehicle.Vin == null
|| exposure.VehicleIncident.Vehicle.Make == null
|| exposure.VehicleIncident.Vehicle.Model == null
|| exposure.VehicleIncident.Vehicle.Year == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if(exposure.VehicleIncident.Vehicle.Vin == null){
  exposure.rejectField("VehicleIncident.Vehicle.Vin", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.Vin, null, null); 
}
if(exposure.VehicleIncident.Vehicle.Make == null){
    exposure.rejectField("VehicleIncident.Vehicle.Make", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.VehicleMake, null, null);
}
if(exposure.isVehicleAListedPolicyVehicle() && exposure.VehicleIncident.Vehicle.Model == null){
    exposure.rejectField("VehicleIncident.Vehicle.Model", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.VehicleModel, null, null); 
}
if(exposure.VehicleIncident.Vehicle.Year == null){
    exposure.rejectField("VehicleIncident.Vehicle.Year", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.VehicleYear, null, null); 
}/*end00rule*/
  }
}
