package rules.Validation.ExposureClosedValidationRules_dir.ECVAG1000AgribusinessExposureClosedValidationRules_dir.ECVAG1100TotalLossFieldsRequiredforISO_dir

@gw.rules.RuleName("ECVAG1110 - Total Loss Indicator Required")
internal class ECVAG1110TotalLossIndicatorRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.TotalLossIndExt == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("TotalLossIndExt", ValidationLevel.TC_ISO, displaykey.Rules.Validation.ExposureClosed.TotalLoss.TotalLossIndicatorNull, null, null); 
actions.exit();/*end00rule*/
  }
}
