package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TXV06000 - Reserve threshold")
internal class TXV06000Reservethreshold {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Subtype == "reserveset" &&
transactionSet.ClaimAmount.Amount > 1000000/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/transactionSet.reject(
  "newloss", displaykey.Rules.Validation.Transaction.ReserveTotalNotGreaterThanOneMillion(gw.api.util.CurrencyUtil.renderAsCurrency(gw.api.financials.CurrencyAmount.getStrict(1000000, transactionSet.Claim.Currency))),
  null, null )/*end00rule*/
  }
}
