package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TXV08000 - Check Aggregate Limits")
internal class TXV08000CheckAggregateLimits {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/TransactionSet.isExceedsApplicableLimitIgnoringStatus()/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/TransactionSet.reject(
  null, null, "newloss", displaykey.Rules.Validation.Transaction.ExceedsAggregateLimit )/*end00rule*/
  }
}
