package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TXV09000 - Check Aggregate Deductible")
internal class TXV09000CheckAggregateDeductible {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/TransactionSet.isExceedsApplicableLimitIgnoringStatus("deductible")/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/TransactionSet.reject(
  null, null, "newloss", displaykey.Rules.Validation.Transaction.ExceededAggregateDeductible )/*end00rule*/
  }
}
