package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAAEQ100 - Equine Global Activity Assignment Rules")
internal class GAAEQ100EquineGlobalActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*///* Run child rules/*end00rule*/
  }
}
