package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAAFC100 - FidCrime Global Assignment Rules")
internal class GAAFC100FidCrimeGlobalAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType=="FIDCRIME" or
activity.Claim.LossType=="KIDNAPRANSOM"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
