package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAAIM100 - PIM Global Activity Assignment Rules")
internal class GAAIM100PIMGlobalActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
