package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAASP100 - Specialty E&S Global Activity Assignment Rules")
internal class GAASP100SpecialtyESGlobalActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType == LossType.TC_SPECIALTYES /*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
