package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAAWC100 - Workers' Comp Global Activity Assignment Rules")
internal class GAAWC100WorkersCompGlobalActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(activity.Claim)/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
