package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAAXX100 - All BUs Global Activity Assignment Rules")
internal class GAAXX100AllBUsGlobalActivityAssignmentRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
