package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1170IncidentOnly_dir

@gw.rules.RuleName("CVXX1171 - Incident Only Value Required")
internal class CVXX1171IncidentOnlyValueRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.IncidentReport == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "IncidentReport", "newloss", "Incident report yes\\no value must be selected.", null, null )/*end00rule*/
  }
}
