package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1170IncidentOnly_dir

@gw.rules.RuleName("CVXX1172 - Prevent I/O Claim If Features Exist")
internal class CVXX1172PreventIOClaimIfFeaturesExist {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.IncidentReport==true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/
if(claim.Exposures.length > 0){
  claim.rejectField( "IncidentReport", "newloss", "You cannot change a claim with Features to Incident Only.", null, null )
}/*end00rule*/
  }
}
