package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CPUAC1000 - ACLs Claim PreUpdate Rules")
internal class CPUAC1000ACLsClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
