package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUBS1000 - Bonds PreUpdate Rules")
internal class CPUBS1000BondsPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == typekey.LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
