package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUEX1000 - Excess Claim PreUpdate Rules")
internal class CPUEX1000ExcessClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/(claim.LossType=="EXCESSLIABILITY" ||
claim.LossType=="EXCESSLIABILITYAUTO")/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
