package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUEQ1000 - Equine Claim PreUpdate Rules")
internal class CPUEQ1000EquineClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*///* Run Child rules/*end00rule*/
  }
}
