package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUEL1000 - ELD Claim PreUpdate Rules")
internal class CPUEL1000ELDClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "EXECLIABDIV" || claim.LossType == LossType.TC_MERGACQU || claim.LossType == LossType.TC_SPECIALHUMSERV/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
