package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUEN1000 - Environmental Claim PreUpdate Rules")
internal class CPUEN1000EnvironmentalClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "ENVLIAB"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
