package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUFC1000 - FIDCRIME Claim PreUpdate Rules")
internal class CPUFC1000FIDCRIMEClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "FIDCRIME" or
claim.LossType == "KIDNAPRANSOM"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
