package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUIM1000 - PIM Claim PreUpdate Rules")
internal class CPUIM1000PIMClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
