package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUPL1000 - PLD Claim PreUpdate Rules")
internal class CPUPL1000PLDClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "PROFLIABDIV"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
