package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUSP1000 - Specialty E&S Pre-update Rules")
internal class CPUSP1000SpecialtyESPreupdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType ==  LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
