package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPUWC1000 - Workers' Comp Claim PreUpdate Rules")
internal class CPUWC1000WorkersCompClaimPreUpdateRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)
/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
