package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir

@gw.rules.RuleName("PVXX11F0 - Reject bad producer code")
internal class PVXX11F0Rejectbadproducercode {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.ProducerCode != null and
policy.ex_Agency == null    
/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.reject( "newloss", displaykey.Java.NewPolicy.Warning.ProducerNotFound, null, null)/*end00rule*/
  }
}
