package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir

@gw.rules.RuleName("PVXX1170 - Unverified Reason on Unverified Policy Required")
internal class PVXX1170UnverifiedReasononUnverifiedPolicyRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified &&
policy.UnverifiedRsnExt == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*///djohnson - Moved from Equine to global and turned this rule back on.
// def 432 by Otteson on 7/30/2007.  Require unverified reason when Policy is in unverified status
policy.rejectField( "UnverifiedRsnExt",
                                    "newloss",
                                    "The \"Reason for Unverified Policy\" field is required when the Policy is in unverified status.",
                                    null,
                                    null )/*end00rule*/
  }
}
