package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir

@gw.rules.RuleName("PVXX1160 - Policy Symbol (Policy Type) Required")
internal class PVXX1160PolicySymbolPolicyTypeRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.PolicyType == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "PolicyType", "newloss", "The claim's policy symbol must not be null", null, null );/*end00rule*/
  }
}
