package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir

@gw.rules.RuleName("PVXX1150 - Policy Number")
internal class PVXX1150PolicyNumber {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and
policy.PolicyNumber == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "PolicyNumber", "newloss", "The claim's policy number must not be null", null, null );/*end00rule*/
  }
}
