package rules.Validation.ExposureValidationRules_dir.EVIM1000PIMExposureValidationRules_dir

@gw.rules.RuleName("EVIM1200 - ISO Validation")
internal class EVIM1200ISOValidation {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
