package rules.Validation.ClaimValidationRules_dir.CVFC1000FidCrimeClaimValidationRules_dir.CVFC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVFC1210 - Code Name is Required")
internal class CVFC1210CodeNameisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.CodeNameExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "CodeNameExt", "payment", displaykey.Rules.Validation.Claim.KR.CodeName, null, null )/*end00rule*/
  }
}
