package rules.Validation.ClaimValidationRules_dir.CVFC1000FidCrimeClaimValidationRules_dir.CVFC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVFC1220 - Broker Policy Number is Required")
internal class CVFC1220BrokerPolicyNumberisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.BrokerPolicyNumberExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "BrokerPolicyNumberExt", "payment", displaykey.Rules.Validation.Claim.KR.BrokerPolicyNum, null, null )/*end00rule*/
  }
}
