package rules.Validation.ClaimValidationRules_dir.CVFC1000FidCrimeClaimValidationRules_dir

@gw.rules.RuleName("CVFC1200 - Validation at Ability to Pay Level")
internal class CVFC1200ValidationatAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="KIDNAPRANSOM"
//dnmiller 3/21/14: added ability to pay validations for 
//  K&R fields code name and broker policy number/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
