package rules.Preupdate.ClaimPreupdate_dir.CPUEQ1000EquineClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUEQ1700 - Non Incident Claims")
internal class CPUEQ1700NonIncidentClaims {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignmentStatus == "assigned" &&
claim.IncidentReport == false/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
