package rules.InitialReserve.InitialReserve_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("IREQ1000 - Equine Initial Reserve Rules")
internal class IREQ1000EquineInitialReserveRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
