package rules.Presetup.TransactionSetPresetup_dir

@gw.rules.RuleName("TPRXX1000 - All Business Unit")
internal class TPRXX1000AllBusinessUnit {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
