package rules.Validation.ExposureValidationRules_dir.EVPA1000PersonalAutoExposureValidationRules_dir

@gw.rules.RuleName("EVPA1100 - Exposure Number Validation")
internal class EVPA1100ExposureNumberValidation {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.New and
Exposure.Claim.ConvertedClaimIndExt and
Exposure.ClaimOrder == 000/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var msg = "Feature Number must be greater than 000."//displaykey.NVV.Exposure.Claimant.CMS.Gender(exposure.Claimant)

exposure.reject("newloss", msg, null, null )/*end00rule*/
  }
}
