package rules.Validation.ExposureValidationRules_dir.EVAG1000AgriBusinessExposureValidationRules_dir

@gw.rules.RuleName("EVAG1100 - Valid for New Loss")
internal class EVAG1100ValidforNewLoss {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType!=LossType.TC_ALTMARKETSAUTO 
AND exposure.Claim.LossType!=LossType.TC_SHSAUTO
AND exposure.Claim.LossType!=LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
