package rules.Validation.ExposureValidationRules_dir.EVCA1000CommercialAutoExposureValidationRules_dir

@gw.rules.RuleName("EVCA1200 - Ability to Pay Field Requirements")
internal class EVCA1200AbilitytoPayFieldRequirements {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
