package rules.Validation.ClaimValidationRules_dir.CVAG1000AgribusinessClaimValidationRules_dir

@gw.rules.RuleName("CVAG1200 - Validation at the Ability to Pay Level")
internal class CVAG1200ValidationattheAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
