package rules.Validation.ClaimValidationRules_dir.CVAG1000AgribusinessClaimValidationRules_dir

@gw.rules.RuleName("CVAG1100 - Validation at New Loss Level")
internal class CVAG1100ValidationatNewLossLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
