package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleName("PVXX1289 - Policy Status Required")
internal class PVXX1289PolicyStatusRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified &&
policy.Status==null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/try {
  policy.rejectField( "Status", "payment", displaykey.Rules.Validation.Policy.Enterprise.AbilityToPay.PolicyStatus, null, null );  
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( policy, actions.getRule() as java.lang.String, e, null )
}/*end00rule*/
  }
}
