package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("PVXX1220 - Producer Code")
internal class PVXX1220ProducerCode {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.ProducerCode == null
//10.29.15 - cmullin - Defect 7750 - Producer information moved from ATP to New Loss Policy Validation (Enterprise). Rule disabled./*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "ProducerCode", "payment", "Producer Code must not be left blank.", null, null )/*end00rule*/
  }
}
