package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleName("PVXX1230 - Issuing Company")
internal class PVXX1230IssuingCompany {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.IssuingCompanyExt == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "IssuingCompanyExt", "payment", displaykey.Rules.Validation.Policy.Enterprise.AbilityToPay.IssuingCo, null, null )/*end00rule*/
  }
}
