package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("PVXX1280 - Profit Center Required")
internal class PVXX1280ProfitCenterRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*///Sprzygocki 2/9/10 - This rule was disabled, but is listed in the Validation rules
//document as required - added back per Joe.
//10.30.15 - cmullin - moved to New Loss validation. See PVXX11K7.

policy.ex_Agency.ex_AgencyProfitCenter == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField("ex_Agency.ex_AgencyProfitCenter", "payment", displaykey.Rules.Validation.PolicyProfitCenter.Blank, null, null )/*end00rule*/
  }
}
