package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("PVXX1290-Underwriter Required")
internal class PVXX1290UnderwriterRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.underwriter == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "Underwriter", "payment","Underwriter must not be left blank.", null, null )/*end00rule*/
  }
}
