package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleName("PVXX1250 - Currency Type Required")
internal class PVXX1250CurrencyTypeRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*///Defect 1482 - mmanalili Currency Type is required for Ability to Pay
!policy.Verified and 
policy.CurrencyTypeExt == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "CurrencyTypeExt", "payment", displaykey.Rules.Validation.Policy.Enterprise.AbilityToPay.CurrencyType, null, null )


/*end00rule*/
  }
}
