package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir

@gw.rules.RuleName("PVXX1240 - RULES FOR ISO AND ATP")
internal class PVXX1240RULESFORISOANDATP {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Claim.ISOEnabled/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
