package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir.PVXX1240RULESFORISOANDATP_dir

@gw.rules.RuleName("PVXX1241 - Insured Requirements")
internal class PVXX1241InsuredRequirements {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*///Stephanie Przygocki 2/10/10
!policy.Verified and 
policy.isPolicyInRefresh( 0 )  //only run when the policy is not in refresh mode
                                //first cycle of policy validation contact is null although
                                //it does exist, and is checked on second cycle./*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
