package rules.Closed.ClaimClosed_dir

@gw.rules.RuleName("CCEN1000 - Environmental Claim Closed Rules")
internal class CCEN1000EnvironmentalClaimClosedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_ENVLIAB/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
