package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1360 - RULES FOR ISO AND ATP")
internal class CVXX1360RULESFORISOANDATP {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*///These rules are those that are required for both ISO and ATP
//If ISO is not enabled, these rules which are in the ISO ruleset will not run
//but they are still required on the claim for ATP validation
!Claim.ISOEnabled/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
