package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1310 - Policy Must Be At ATP")
internal class CVXX1310PolicyMustBeAtATP {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Policy.ValidationLevel !="payment" /*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "payment", "Policy must be at ability to pay.", null, null )/*end00rule*/
  }
}
