package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1370 - County Required for Profit Center 3541")
internal class CVXX1370CountyRequiredforProfitCenter3541 {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Policy.ex_Agency.ex_AgencyProfitCenter != null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/if(claim.Policy.ex_Agency.ex_AgencyProfitCenter.equalsIgnoreCase("3541")){
  if(claim.LossLocation.County == null)
  {
   claim.reject( "payment", "County is required for Ability to Pay.", null, null )    
  }
 }/*end00rule*/
  }
}
