package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1350 - Close Reason Required")
internal class CVXX1350CloseReasonRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Closed and claim.ClosedOutcome==null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try{
  claim.reject( "payment", "A closed claim must have a close reason", null, null )
} catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
