package rules.Closed.MatterClosed_dir

@gw.rules.RuleName("CMC01000 - Set Litigation Status")
internal class CMC01000SetLitigationStatus {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.Matters.where(\ m -> m.Closed==false).Count == 0/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/matter.Claim.LitigationStatus = "complete"/*end00rule*/
  }
}
