package rules.Exception.GroupExceptionRules_dir

@gw.rules.RuleName("GEAG1000 - AgriBusiness Group Exception Rules")
internal class GEAG1000AgriBusinessGroupExceptionRules {
  static function doCondition(group : entity.Group) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(group : entity.Group, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
