package rules.Assignment.DefaultGroupMatterAssignmentRules_dir

@gw.rules.RuleName("DGMAIM100 - PIM Default Group Matter Assignment Rules")
internal class DGMAIM100PIMDefaultGroupMatterAssignmentRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
