package rules.Assignment.DefaultGroupMatterAssignmentRules_dir

@gw.rules.RuleName("DGMAEQ100 - Equine Default Group Matter Assignment Rules")
internal class DGMAEQ100EquineDefaultGroupMatterAssignmentRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/Matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
