package rules.Preupdate.MatterAssignmentExtPreupdate_dir.MAPUXX1000AllBUsPreUpdateRules_dir.MAPUXX1400GenerateActivitiesFromLitAdvisorUpdates_dir

@gw.rules.RuleName("MAPUXX1420 - New Staffing Plan Received")
internal class MAPUXX1420NewStaffingPlanReceived {
  static function doCondition(matterAssignmentExt : entity.MatterAssignmentExt) : boolean {
    return /*start00rule*/matterAssignmentExt.ChangedFields.contains("StaffingPlanExt") &&
!exists(act in matterAssignmentExt.Matter.Claim.Activities 
where act.ActivityPattern == ActivityPattern.finder.getActivityPatternByCode("new_staffing_plan") 
      and act.MatterAssignmentExt == matterAssignmentExt
      and act.Status == ActivityStatus.TC_OPEN)

/*
 If a new staffing plan has been submitted from LSS and there
 is not currently an open activity then generate a new activity to the
 adjuster 
*//*end00rule*/
  }

  static function doAction(matterAssignmentExt : entity.MatterAssignmentExt, actions : gw.rules.Action) {
/*start00rule*/try{
        
      //get the new staffing plan activity pattern
      var pattern = ActivityPattern.finder.getActivityPatternByCode( "new_staffing_plan" )
     
      //get exposure related to primary claimant
      var exposure = matterAssignmentExt.AssignmentExposuresExt.where(\ a -> a.PrimaryClaimantExt == true)*.Exposure.first()
      
      //Create new activity from existing pattern and add the matter name to the pattern
      //subject and description  
      var newAct = matterAssignmentExt.Matter.Claim
          .createActivity(exposure, pattern,
           pattern.Subject + " (" + matterAssignmentExt.CounselLawFirmExt + ") for the Legal Action (" + matterAssignmentExt.Matter.DisplayName + ")",
           pattern.Description + " (" + matterAssignmentExt.CounselLawFirmExt + ") for the Legal Action (" + matterAssignmentExt.Matter.DisplayName + ")",
           pattern.Priority, pattern.Mandatory, gw.api.util.DateUtil.currentDate(), null)
      
      
      //associate matter & matterAssignmentExt
      newAct.Matter = matterAssignmentExt.Matter
      newAct.MatterAssignmentExt = matterAssignmentExt
      
      //assign the activity to the user assigned to the claim
      newAct.AssignedUser = matterAssignmentExt.Matter.Claim.AssignedUser
     
  }catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( matterAssignmentExt, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
