package rules.Validation.ClaimValidationRules_dir.CVAC1000CommercialAutoValidationRules_dir

@gw.rules.RuleName("CVAC1100 - Validation at Ability to Pay Level")
internal class CVAC1100ValidationatAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
