package rules.Workplan.ClaimWorkplan_dir.CLW07000Workerscompclaims_dir

@gw.rules.RuleName("CLW07300 - New users")
internal class CLW07300Newusers {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignedUser.ExperienceLevel == "low"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
