package rules.Validation.ClaimValidationRules_dir.CVPL1000ProfessionalLiabilityClaimValidationRules_dir.CVEL1400ValidationattheISOLevel_dir

@gw.rules.RuleName("CVEL1420 - Bodily Injury is Required")
internal class CVEL1420BodilyInjuryisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.BodilyInjuryExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField("BodilyInjuryExt", "iso", displaykey.Rules.Validation.Claim.ExecutiveLiability.BodilyInjury, null, null)/*end00rule*/
  }
}
