package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVAG1000 - Agribusiness Claim Closed Validation Rules")
internal class CCVAG1000AgribusinessClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossType == "AGRIAUTO" ||
Claim.LossType == "AGRILIABILITY" ||
Claim.LossType == "AGRIPROPERTY" OR 
claim.LossType==LossType.TC_ALTMARKETSAUTO OR 
claim.LossType==LossType.TC_SHSAUTO OR 
claim.LossType==LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
