package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVBS1000 - Bonds Claim Closed Validation Rules")
internal class CCVBS1000BondsClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == typekey.LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
