package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVEQ1000 - Equine Claim Closed Validation Rules")
internal class CCVEQ1000EquineClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
