package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVFC1000 - FidCrime Claim Closed Validation Rules")
internal class CCVFC1000FidCrimeClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == typekey.LossType.TC_FIDCRIME ||
claim.LossType == typekey.LossType.TC_KIDNAPRANSOM/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
