package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVSP1000 - Specialty E&S Claim Closed Validation Rules")
internal class CCVSP1000SpecialtyESClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
