package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVWC1000 - Workers Comp Claim Closed Validation Rules")
internal class CCVWC1000WorkersCompClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)
/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
