package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVXX1000 - All BU Claim Closed Validation Rules")
internal class CCVXX1000AllBUClaimClosedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
