package rules.Validation.ClaimReopenedValidationRules_dir

@gw.rules.RuleName("CRVAG1000 - AgriBusiness Claim Reopen Validation Rules")
internal class CRVAG1000AgriBusinessClaimReopenValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AGRIAUTO" ||
claim.LossType == "AGRILIABILITY" ||
claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
