package rules.Validation.ClaimReopenedValidationRules_dir

@gw.rules.RuleName("CRVEQ1000 - Equine Claim Reopen Validation Rules")
internal class CRVEQ1000EquineClaimReopenValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
