package rules.Validation.ClaimReopenedValidationRules_dir

@gw.rules.RuleName("CRVWC1000 - Workers Comp Claim Reopened Validation Rules")
internal class CRVWC1000WorkersCompClaimReopenedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
