package rules.Validation.ClaimReopenedValidationRules_dir

@gw.rules.RuleName("CRVXX1000 - All BUs Claim Reopened Validation Rules")
internal class CRVXX1000AllBUsClaimReopenedValidationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
