package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1200ValidationattheISOLevel_dir

@gw.rules.RuleName("CVXX1210 - Prevent ISO at Draft status")
internal class CVXX1210PreventISOatDraftstatus {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.State=="draft"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "iso", " Claim cannot be in Draft status", null, null )/*end00rule*/
  }
}
