package rules.Assignment.GlobalMatterAssignmentRules_dir.GMAXX100AllBUGlobalMatterAssignmentRules_dir

@gw.rules.RuleName("GMAXX999 - Last Resort")
internal class GMAXX999LastResort {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/matter.CurrentAssignment.assignToIssueOwner()/*end00rule*/
  }
}
