package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("GAA05000 - Homeowners PolicyType")
internal class GAA05000HomeownersPolicyType {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/Activity.Claim.Policy.PolicyType == "homeowners"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
