package rules.EventMessage.EventFired_dir.Destination6LitAdvisor_dir

@gw.rules.RuleName("Check")
internal class Check {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Check && 
!gaic.conversion.util.ConversionStatusChecker.isCurrentlyConverting(messageContext.Root.Claim.LoadCommandID)
&& messageContext.EventName == "CheckStatusChanged"
&& util.gaic.LitAdvisorFunctions.sendToLSS(messageContext.Root.Claim.LossType)/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
