package rules.EventMessage.EventFired_dir.Destination6LitAdvisor_dir

@gw.rules.RuleName("Exposure")
internal class Exposure {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Exposure &&
!gaic.conversion.util.ConversionStatusChecker.isCurrentlyConverting(messageContext.Root.Claim.LoadCommandID) 
&& (messageContext.EventName == "ExposureAdded"
  || messageContext.EventName == "ExposureChanged")
&& util.gaic.LitAdvisorFunctions.sendToLSS(messageContext.Root.Claim.LossType)/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
