package rules.Assignment.DefaultGroupClaimAssignmentRules_dir

@gw.rules.RuleName("DGCAEQ100 - Equine Default Claim Assignment Rules")
internal class DGCAEQ100EquineDefaultClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules specific to Equine Line of Business*//*end00rule*/
  }
}
