package rules.Assignment.DefaultGroupClaimAssignmentRules_dir

@gw.rules.RuleName("DGCAXX100 - All BUs Default Group Claim Assignment Rules")
internal class DGCAXX100AllBUsDefaultGroupClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules common across all Lines of Business*//*end00rule*/
  }
}
