package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir.TVXX1100CheckSetRules_dir

@gw.rules.RuleName("TVXX11B0 - Recurring Checks")
internal class TVXX11B0RecurringChecks {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/(transactionSet as CheckSet).Recurrence != null/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
