package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1130DateReportedRequirements_dir

@gw.rules.RuleName("CVXX1131 - Date Reported is Required")
internal class CVXX1131DateReportedisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ReportedDate==Null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*

*/

var msg:String
msg="Please provide the value for the date the Claim was reported."


claim.rejectField( "ReportedDate", "newloss", msg, Null, Null )/*end00rule*/
  }
}
