package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1165 - Cause Of Injury")
internal class CVWC1165CauseOfInjury {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossCause==null && !claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "LossCause", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.CauseOfInjury, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
