package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1130 - SSN Required")
internal class CVWC1130SSNRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.TaxID == null && 
claim.InjuredWorker.UndocumentedWorkerExt != true &&
claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "claimant.TaxID", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.SSN, null, null )
}
catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
