package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1105 - Attorney Rep")
internal class CVWC1105AttorneyRep {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AttorneyRepExt==null &&
!claim.IncidentReport &&
claim.New/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "AttorneyRepExt", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.AttorneyRep, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
