package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1135 - Minor Child")
internal class CVWC1135MinorChild {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.InjuredWorker.MinorWorkerExt==null &&
!claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "InjuredWorker.MinorWorkerExt", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.MinorChild, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
