package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1175 - Lost Time From Work")
internal class CVWC1175LostTimeFromWork {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.TimeLossReport==null && 
!claim.IncidentReport && 
util.WCHelper.isWCLossType(claim)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "TimeLossReport", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.LostTime, null, null )
}
catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
