package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1150 - Loss Location Zip Code")
internal class CVWC1150LossLocationZipCode {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossLocation.State == "tx" && claim.LossLocation.PostalCode == null
//10.15.15 - cmullin - Requirements change. This field will be required on the screen only.
//No rule required for converted claims. Rule disabled./*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "LossLocation.PostalCode", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.ZipCode, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
