package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1195 - Reserved File")
internal class CVWC1195ReservedFile {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ReservedFileExt==null && 
!claim.IncidentReport &&
claim.New/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "ReservedFileExt", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.ReservedFile, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
