package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1170 - Gender")
internal class CVWC1170Gender {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.Gender == null &&
claim.IncidentReport != true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
  claim.rejectField( "claimant.Gender", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.Gender, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
