package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1100ValidationatNewLossLevel_dir

@gw.rules.RuleName("CVWC1145 - Claimant Deceased")
internal class CVWC1145ClaimantDeceased {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.ClaimantFatalityExt==null &&
!claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "claimant.ClaimantFatalityExt", "newloss", displaykey.Rules.Validation.Claim.WorkersComp.ClaimantDeceased, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
