package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir.ECVXX1400MethodofSettlement_dir

@gw.rules.RuleName("ECVXX1410 - Method of Settlement is null")
internal class ECVXX1410MethodofSettlementisnull {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*Check if Method of Settlement has been entered on a Bodily Injury feature before a payment is issued.
  This performs a validation check for an instance of a user entering a final payment for a check on a 
  Bodily injury feature where Method of Settlement has not been entered.
  Sprint: Sprint 8
  Author: Stephanie Przygocki
  Date: 10-19-07
  Updated: 5/1/08 - Stephanie Przygocki
  Updated: 5/8/08 - Eric Rawe - Added claimcost check
  Updated: 7/14/09 - Stephanie Przygocki - put the for in an exists() in the condition and added
     a check for if it is the same exposure, not just if there is a partial loss payment existing on the claim
  */
exposure.MethodOfSettlementExt==null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "payment", displaykey.Rules.Validation.ExposureClosed.AgriBusiness.AbilityToPay.MethodOfSettlement(exposure), null, null )
/*end00rule*/
  }
}
