package rules.Preupdate.ClaimPreupdate_dir.CPUXX1000GlobalBuisnessPreUpdateRules_dir.CPUXX1AA0ISO_dir

@gw.rules.RuleName("CPUXX1AA1 - Validate ISO")
internal class CPUXX1AA1ValidateISO {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ValidationLevel=="newloss" ||
claim.ValidationLevel=="loadsave"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.isoValidate();/*end00rule*/
  }
}
