package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05720NormalVehicle_dir

@gw.rules.RuleName("EXV05721 - Vin Present")
internal class EXV05721VinPresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.LossParty != "third_party" 
and exposure.VehicleIncident.Vehicle.Year >= 1981
and exposure.VehicleIncident.Vehicle.Vin == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.VehicleIdNumberRequired, null, null )/*end00rule*/
  }
}
