package rules.Postsetup.ClaimPostsetup_dir

@gw.rules.RuleName("CPOAG1000 - AgriBusiness Claim PostSetup Rules")
internal class CPOAG1000AgriBusinessClaimPostSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="agriproperty" || 
claim.LossType== "agriliability" || 
claim.LossType== "agriauto"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
