package rules.Postsetup.ClaimPostsetup_dir

@gw.rules.RuleName("CPOBS1000 - Bonds Claim PostSetup Rules")
internal class CPOBS1000BondsClaimPostSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == typekey.LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
