package rules.Postsetup.ClaimPostsetup_dir

@gw.rules.RuleName("CPOEQ1000 - Equine Claim PostSetup Rules")
internal class CPOEQ1000EquineClaimPostSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
