package rules.Postsetup.ClaimPostsetup_dir

@gw.rules.RuleName("CPOIM1000 - PIM Claim PostSetup Rules")
internal class CPOIM1000PIMClaimPostSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
