package rules.Presetup.ClaimPresetup_dir

@gw.rules.RuleName("CPRAG1000 - AgriBusiness Claim Pre Setup Rules")
internal class CPRAG1000AgriBusinessClaimPreSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AGRIAUTO" ||
claim.LossType == "AGRILIABILITY" ||
claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
