package rules.Presetup.ClaimPresetup_dir

@gw.rules.RuleName("CPREQ1000 - Equine Claim Pre Setup Rules")
internal class CPREQ1000EquineClaimPreSetupRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
