package rules.ActivityGeneratorBatch.ActivityGeneratorBatchRules_dir.ABXX1000AExclusionfilters_dir

@gw.rules.RuleName("ABBS1000 - Bonds Activity Batch Rules")
internal class ABBS1000BondsActivityBatchRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == typekey.LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
