package rules.ActivityGeneratorBatch.ActivityGeneratorBatchRules_dir.ABXX1000AExclusionfilters_dir

@gw.rules.RuleName("ABXX2000 - Specialty E&S Activity Batch Rules")
internal class ABXX2000SpecialtyESActivityBatchRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
