package rules.Validation.ExposureValidationRules_dir.EVIM1000PIMExposureValidationRules_dir.EVIM1300AbilitytoPayValidation_dir

@gw.rules.RuleName("EVIM1310 - Law/Ord Question required")
internal class EVIM1310LawOrdQuestionrequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == "im_Building" ||
exposure.ExposureType == "im_PropOfOthers" ||
exposure.ExposureType == "im_PersonalProp" ||
exposure.ExposureType == "im_BusinessInc"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var errorMsg = "Question \"Does this feature involve Ordinance or Law?\" is required for Ability to Pay."

if(exposure.InvolveLawOrdExt==null){
  exposure.rejectField( "InvolveLawOrdExt", "payment", errorMsg, null, null )
}/*end00rule*/
  }
}
