package rules.Validation.ExposureValidationRules_dir.EVIM1000PIMExposureValidationRules_dir.EVIM1300AbilitytoPayValidation_dir

@gw.rules.RuleName("EVIM1320 - Green Question Required")
internal class EVIM1320GreenQuestionRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == "im_Building" ||
exposure.ExposureType == "im_PropOfOthers" ||
exposure.ExposureType == "im_PersonalProp" ||
exposure.ExposureType == "im_BusinessInc"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var errorMsg = "Question \"Does this feature involve Green Coverage?\" is required for Ability to Pay."

if(exposure.InvolveGreenCvgExt==null){
  exposure.rejectField( "InvolveGreenCvgExt", "payment", errorMsg, null, null )}/*end00rule*/
  }
}
