package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir

@gw.rules.RuleName("CVXX1100 - Validation at the ISO Level ")
internal class CVXX1100ValidationattheISOLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
