package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir

@gw.rules.RuleName("CVXX1200 - Validation at Ability to Pay Level")
internal class CVXX1200ValidationatAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
