package rules.Reopened.ExposureReopened_dir

@gw.rules.RuleName("ERO01000 - Notify external systems")
internal class ERO01000Notifyexternalsystems {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true /* always notify *//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.Claim.addEvent(  "exposure_reopened" )/*end00rule*/
  }
}
