package rules.Validation.ClaimClosedValidationRules_dir

@gw.rules.RuleName("CCV07000 - Open matters")
internal class CCV07000Openmatters {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/exists (
 Matter in Claim.Matters
 where not (Matter.Closed) 
)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "newloss",
 displaykey.Rules.Validation.CloseClaim.CloseAllOpenMatters,
 null, null )/*end00rule*/
  }
}
