package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVIM1000PIMPolicyValidationRules_dir.PVIM1100NewLossLevel_dir

@gw.rules.RuleName("PVIM1130 - Prevent Duplicate Properties")
internal class PVIM1130PreventDuplicateProperties {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified && policy.Properties.Count > 1/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/var validationError = policy.validatePropertyUniqueness()
  
if(!validationError.isEmpty()){
  policy.reject(ValidationLevel.TC_NEWLOSS, validationError, null, null) 
}/*end00rule*/
  }
}
