package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVIM1000PIMPolicyValidationRules_dir.PVIM1100NewLossLevel_dir

@gw.rules.RuleName("PVIM1110 - Prevent Duplicate Building Number On Premises")
internal class PVIM1110PreventDuplicateBuildingNumberOnPremises {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified && policy.Properties.countWhere(\ prop -> 
   prop.Property.RiskTypeExt == EDWRiskType.TC_BLDG) > 1
/*
  Defect 4982: tnewcomb 01/27/2012
  This rule rejects any policies that have more than 1 property with the same
  Premises Number/Building Number combination, when Risk Type is Building.
*/
/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/try{
  var validationError = policy.validatePremisesBuildingCombo()

  if(!validationError.isEmpty()){
    policy.reject(ValidationLevel.TC_NEWLOSS, validationError, null, null)
    actions.exit()
  }
}catch(aex:gw.rules.AbortExecutionException){
  throw aex
}catch(e){
  gw.api.util.Logger.logError("An error has occurred in the rule: " +
    actions.Rule.DisplayName + ".\nStack Trace: \n" + e) 
}/*end00rule*/
  }
}
