package rules.Assignment.GlobalClaimAssignmentRules_dir.GCAXX100AllBUsGlobalClaimAssignmentRules_dir

@gw.rules.RuleName("GCAXX999 - Last Resort")
internal class GCAXX999LastResort {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
