package rules.ApprovalRouting.ApprovalRules_dir

@gw.rules.RuleName("ARXX1000 - All BUs Approval Routing Rules")
internal class ARXX1000AllBUsApprovalRoutingRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
