package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVEQ1000EquinePolicyValidationRules_dir.PVEQ1300AbilitytoPay_dir

@gw.rules.RuleName("PVEQ1310 - Properties Required")
internal class PVEQ1310PropertiesRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*///We need a property to exist on the policy before it can go to ATP for Equine, somehow this was missed
//Stephanie Przygocki - copied from Claim Validation
//2/1/10
policy.Properties.length == 0/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.reject( "payment", "Policy must have a property to reach ability to pay.", null, null )/*end00rule*/
  }
}
