package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVEQ1000EquinePolicyValidationRules_dir.PVEQ1300AbilitytoPay_dir

@gw.rules.RuleName("PVEQ1320 - Animal Name Required")
internal class PVEQ1320AnimalNameRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and
exists ( prop in policy.Properties where prop.Property.LocationNumber==null) /*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.reject("payment", displaykey.Rules.Validation.PolicyAnimalNameBlank, null, null) /*end00rule*/
  }
}
