package rules.Validation.TransactionSetValidationRules_dir.TVIM1000PIMTransactionValidationRules_dir

@gw.rules.RuleName("TVIM1100 - Reserve Rules")
internal class TVIM1100ReserveRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Subtype=="ReserveSet"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
