package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPUEQ1000 - Equine Transaction PreUpdate Rules")
internal class TPUEQ1000EquineTransactionPreUpdateRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/actions.exitAfter()/*end00rule*/
  }
}
