package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPUEN1000 - ENV Transaction PreUpdate Rules")
internal class TPUEN1000ENVTransactionPreUpdateRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType == "ENVLIAB"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
