package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPUIM1000 - PIM Transaction PreUpdate Rules")
internal class TPUIM1000PIMTransactionPreUpdateRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
