package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPUSP1000 - Specialty E&S Transaction PreUpdate Rules")
internal class TPUSP1000SpecialtyESTransactionPreUpdateRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType == "SPECIALTYES"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
