package rules.Preupdate.TransactionSetPreupdate_dir

@gw.rules.RuleName("TPUXX1000 - All BU Transaction Pre Update")
internal class TPUXX1000AllBUTransactionPreUpdate {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
