package rules.Preupdate.ClaimPreupdate_dir.CPUAG1000AgriBusinessClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUAG1200 - Non Incident Only Claims")
internal class CPUAG1200NonIncidentOnlyClaims {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignmentStatus == "assigned" &&
claim.IncidentReport == false/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
