package rules.Reopened.MatterReopened_dir

@gw.rules.RuleName("MRO01000 - Set Litigation Status")
internal class MRO01000SetLitigationStatus {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/matter.Claim.LitigationStatus = "litigated"/*end00rule*/
  }
}
