package rules.Postsetup.ClaimPostsetup_dir.CPOXX1000AllBUsClaimPostSetup_dir

@gw.rules.RuleName("CPOXX1200 - New Claim Creation")
internal class CPOXX1200NewClaimCreation {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.touch();
claim.addEvent("NewClaim")/*end00rule*/
  }
}
