package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV05000 - Policy expiration date after effective date")
internal class CLV05000Policyexpirationdateaftereffectivedate {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.Policy.EffectiveDate > Claim.Policy.ExpirationDate/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectSubField( Claim.Policy, "effectivedate",
                                "newloss",
                                displaykey.Rules.Validation.Claim.PolicyExpirationLaterThanEffectiveDate,
                                null,
                                null )/*end00rule*/
  }
}
