package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CLV01000 - Not set: Coverage in Question")
internal class CLV01000NotsetCoverageinQuestion {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.CoverageInQuestion==null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "CoverageInQuestion", "newloss",
   displaykey.Rules.Validation.Claim.IndicateCoverageInQuestion, null, null )/*end00rule*/
  }
}
