package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV03000 - Future loss date")
internal class CLV03000Futurelossdate {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossDate > gw.api.util.DateUtil.currentDate()/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "LossDate", "newloss",
   displaykey.Rules.Validation.Claim.ProvideLossDateNotInTheFuture, null, null )/*end00rule*/
  }
}
