package rules.Validation.ClaimValidationRules_dir

@gw.rules.RuleName("CLV12000 - Injury diagnosis validity dates")
internal class CLV12000Injurydiagnosisvaliditydates {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.InjuryIncidentsOnly.where( \ i -> i.InjuryDiagnoses.length > 0 ).Count > 0
or Claim.ClaimInjuryIncident.InjuryDiagnoses.length > 0/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
