package rules.Validation.ExposureClosedValidationRules_dir.ECVXX1000AllBUExposureClosedValidationRules_dir.ECVXX1600MedicareRelated_dir

@gw.rules.RuleName("ECVXX1630 - Medicare Eligible False")
internal class ECVXX1630MedicareEligibleFalse {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/(exposure.Claimant as Person).MedicareEligibleExt == false/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
