package rules.Validation.GroupValidationRules_dir.GVXX1000AllBUsGroupValidationRules_dir.GVXX1100CurrentUserUpdatesOnly_dir

@gw.rules.RuleName("GVXX1110 - Bus User Groups Only")
internal class GVXX1110BusUserGroupsOnly {
  static function doCondition(group : entity.Group) : boolean {
    return /*start00rule*/group.GroupType == "technical" or
group.GroupType == "processing" or
group.GroupType == "busunit" or
group.GroupType == "branchoffice" /*end00rule*/
  }

  static function doAction(group : entity.Group, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
