package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09700 - LossDate")
internal class CLV09700LossDate {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossDate == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "LossDate", "iso", displaykey.Rules.Validation.Claim.LossDateNotNull, null, null )/*end00rule*/
  }
}
