package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09600 - ClaimNumber")
internal class CLV09600ClaimNumber {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.ClaimNumber == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "ClaimNumber", "iso", displaykey.Rules.Validation.Claim.ClaimNumberNotNull, null, null )/*end00rule*/
  }
}
