package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV091100 - Description")
internal class CLV091100Description {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ISOClaimLevelMessaging && !claim.Description.HasContent/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "Description", "iso",
                   displaykey.Rules.Validation.Claim.DescriptionNotNull, null, null )/*end00rule*/
  }
}
