package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09800 - State")
internal class CLV09800State {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossLocation.State == null && 
( Claim.LossLocation.Country == null || Claim.LossLocation.Country == Country.TC_US || Claim.LossLocation.Country == Country.TC_CA)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "LossLocation.State", "iso",
                      displaykey.Rules.Validation.Claim.LossLocationStateNotNull, null, null )/*end00rule*/
  }
}
