package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09500 - PolicyType")
internal class CLV09500PolicyType {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.Policy.PolicyType == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "Policy.PolicyType", "iso", displaykey.Rules.Validation.Claim.PolicyTypeNotNull, null, null );/*end00rule*/
  }
}
