package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09100 - Not Draft")
internal class CLV09100NotDraft {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.State == "draft"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "State", "iso", displaykey.Rules.Validation.Claim.NotInDraft, null, null )/*end00rule*/
  }
}
