package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09400 - PolicyNumber")
internal class CLV09400PolicyNumber {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.Policy.PolicyNumber == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "Policy.PolicyNumber", "iso", displaykey.Rules.Validation.Claim.PolicyNumberNotNull, null, null );/*end00rule*/
  }
}
