package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09300 - LossLocation")
internal class CLV09300LossLocation {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.LossLocation == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "LossLocation", "iso", displaykey.Rules.Validation.Claim.LossLocNotNull, null, null )/*end00rule*/
  }
}
