package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir

@gw.rules.RuleName("CLV09200 - Policy")
internal class CLV09200Policy {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Policy == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "Policy", "iso", displaykey.Rules.Validation.Claim.PolicyNotNull, null, null )/*end00rule*/
  }
}
