package rules.Assignment.GlobalExposureAssignmentRules_dir

@gw.rules.RuleName("GEAEQ100 - Equine Global Exposure Assignment Rules")
internal class GEAEQ100EquineGlobalExposureAssignmentRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
