package rules.Assignment.GlobalExposureAssignmentRules_dir

@gw.rules.RuleName("GEAIM100 - PIM Global Exposure Assignment Rules")
internal class GEAIM100PIMGlobalExposureAssignmentRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
