package rules.Assignment.GlobalExposureAssignmentRules_dir

@gw.rules.RuleName("GEAXX100 - All BU Global Exposure Assignment Rules")
internal class GEAXX100AllBUGlobalExposureAssignmentRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*///* RUN CHILD RULES/*end00rule*/
  }
}
