package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CWAG1000 - AgriBusiness Claim Workplan Rules")
internal class CWAG1000AgriBusinessClaimWorkplanRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AGRIAUTO" ||
claim.LossType == "AGRILIABILITY" ||
claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
