package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CWEQ1000 - Equine Claim Workplan Rules")
internal class CWEQ1000EquineClaimWorkplanRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "EQUINE"&&
claim.IncidentReport == false/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
