package rules.Workplan.ClaimWorkplan_dir

@gw.rules.RuleName("CWWC1000 - Workers' Comp Claim Workplan Rules")
internal class CWWC1000WorkersCompClaimWorkplanRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(claim)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
