package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX11K0ProducerRequirements_dir

@gw.rules.RuleName("PVXX11K3 - Producer Code Required")
internal class PVXX11K3ProducerCodeRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.ProducerCode == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/try {
  policy.rejectField( "ProducerCode", "newloss", displaykey.Rules.Validation.Policy.Enterprise.NewLoss.ProducerCode, null, null );  
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( policy, actions.getRule() as java.lang.String, e, null )
}/*end00rule*/
  }
}
