package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX11K0ProducerRequirements_dir

@gw.rules.RuleName("PVXX11K6 - Agency Name Required")
internal class PVXX11K6AgencyNameRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified &&
policy.ex_Agency.Name == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/try {
  policy.rejectField( "ex_Agency", "newloss", displaykey.Rules.Validation.Policy.Enterprise.NewLoss.AgentName, null, null );  
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( policy, actions.getRule() as java.lang.String, e, null )
}/*end00rule*/
  }
}
