package rules.EventMessage.EventFired_dir.Destination6LitAdvisor_dir.Exposure_dir

@gw.rules.RuleName("ExposureAdded")
internal class ExposureAdded {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.EventName == "ExposureAdded"/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/var feature = messageContext.Root as Exposure;
util.gaic.LitAdvisorFunctions.sendExposureChanges( messageContext, feature );/*end00rule*/
  }
}
