package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir.EVISO500BoatPayload_dir

@gw.rules.RuleName("EVISO530 - Boat Year")
internal class EVISO530BoatYear {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/((exposure.Coverage as VehicleCoverage).RiskUnit as VehicleRU).Vehicle.Year == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var reason = "Year is required on the boat: " + ((exposure.Coverage as VehicleCoverage).RiskUnit as VehicleRU).Vehicle

exposure.reject( "iso", reason, null, null )/*end00rule*/
  }
}
