package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir.EVISO500BoatPayload_dir

@gw.rules.RuleName("EVISO520 - Boat Make")
internal class EVISO520BoatMake {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/((exposure.Coverage as VehicleCoverage).RiskUnit as VehicleRU).Vehicle.Make == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var reason = "Make is required on the boat: " + ((exposure.Coverage as VehicleCoverage).RiskUnit as VehicleRU).Vehicle

exposure.reject( "iso", reason, null, null )/*end00rule*/
  }
}
