package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir

@gw.rules.RuleName("PVXX1300 - Valid for ISO")
internal class PVXX1300ValidforISO {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
