package rules.Segmentation.ExposureSegmentationRules_dir

@gw.rules.RuleName("ESEQ1000 - Equine Exposure Segmentation Rules")
internal class ESEQ1000EquineExposureSegmentationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
