package rules.Segmentation.ExposureSegmentationRules_dir

@gw.rules.RuleName("ESXX1000 - All BUs Exposure Segmentation Rules")
internal class ESXX1000AllBUsExposureSegmentationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
