package rules.Validation.MatterReopenedValidationRules_dir.MRVXX1000AllBUsMatterReopenedRules_dir

@gw.rules.RuleName("MRVXX1200 - Need open features with legal expense set to yes")
internal class MRVXX1200Needopenfeatureswithlegalexpensesettoyes {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/!exists(exp in matter.Claim.Exposures where
        !exp.Closed && exp.LegalExpenseExt ==true)/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/try{
    var strErrorReason= "Please set Legal Expense to Yes on at least one open Feature before reopening the Legal Action."
    matter.reject("newloss", strErrorReason, Null, Null) 
    
} catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError(matter, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
