package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir.TVXX1400ChecksetRulesNotTransferredCheck_dir

@gw.rules.RuleName("TVXX1430 - Set Cost Category")
internal class TVXX1430SetCostCategory {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/for(each in transactionSet.Transactions){
  if (each.Subtype =="Payment" and each.CostCategory == null)
       each.CostCategory="unspecified"
}
/*end00rule*/
  }
}
