package rules.Validation.ClaimClosedValidationRules_dir.CCVBS1000BondsClaimClosedValidationRules_dir

@gw.rules.RuleName("CCBBS1100 - Collection Note Required")
internal class CCBBS1100CollectionNoteRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/!claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/if(claim.Notes.where(\ n -> n.Topic == NoteTopicType.TC_COLLECTION ).Count == 0){
 claim.reject("loadsave", "This claim cannot be closed until a Collection Note has been entered.", null, null) 
}/*end00rule*/
  }
}
