package rules.Presetup.ActivityPresetup_dir

@gw.rules.RuleName("APREQ1000 - Equine Activity Pre Setup Rules")
internal class APREQ1000EquineActivityPreSetupRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
