package rules.Presetup.ActivityPresetup_dir

@gw.rules.RuleName("APRXX1000 - All BUs Activity PreSetup Rules")
internal class APRXX1000AllBUsActivityPreSetupRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
