package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUAV1000 - Aviation Exposure Pre-Update Rules")
internal class EPUAV1000AviationExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="AVIATION"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
