package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUBS1000 - Bonds Exposure Pre-Update Rules")
internal class EPUBS1000BondsExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
