package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUEN1000 - Env Exposure Pre-Update Rules")
internal class EPUEN1000EnvExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="ENVLIAB"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
