package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUENV1000 - ENV Exposure Pre-Update Rules")
internal class EPUENV1000ENVExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
