package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUEQ1000 - Equine Exposure PreUpdate Rules")
internal class EPUEQ1000EquineExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
