package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUEX1000 - Excess Exposure PreUpdate Rules")
internal class EPUEX1000ExcessExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="EXCESSLIABILITY" ||
exposure.Claim.LossType=="EXCESSLIABILITYAUTO"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
