package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUFC1000 - FidCrime Exposure PreUpdate Rules")
internal class EPUFC1000FidCrimeExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="FIDCRIME" or 
exposure.Claim.LossType=="KIDNAPRANSOM"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
