package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUIM1000 - PIM Exposure Pre-Update Rules")
internal class EPUIM1000PIMExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
