package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUOM1000 - Ocean Marine PreUpdate Rules")
internal class EPUOM1000OceanMarinePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == LossType.TC_OMAVALON/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
