package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUPL1000 - PLD Exposure Pre-Update Rules")
internal class EPUPL1000PLDExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType=="PROFLIABDIV"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
