package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUSP1000 - Specialty E&S Exposure Pre-Update Rules")
internal class EPUSP1000SpecialtyESExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
