package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUWC1000 - Workers' Comp Exposure Pre-Update Rules")
internal class EPUWC1000WorkersCompExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(exposure.Claim)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
