package rules.Preupdate.ExposurePreupdate_dir

@gw.rules.RuleName("EPUXX1000 - All BU Exposure PreUpdate Rules")
internal class EPUXX1000AllBUExposurePreUpdateRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
