package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1300ValidationatAbilitytoPayLevel_dir.CVXX1340TypeofLoss_dir

@gw.rules.RuleName("CVXX1341 - Loss Cause Changed")
internal class CVXX1341LossCauseChanged {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*//*Checks for a flag for loss cause changes - applicable for sublines 116, 136, 156
  Sprint/Maintenance Release: Sprint 12
  Author: Stephanie Przygocki
  Date: April 2008
  Updated: Stephanie Przygocki - Sprint 13 - 5/9/08 - Added a displaykey for reason
*/

claim.isFieldChanged( "LossCause" ) and
exists(exp in claim.Exposures where exp.LossCauseChangedExt)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( null, null, "newloss", displaykey.Rules.Validation.Claim.AgriBusiness.NewLoss.TypeOfLoss.LossCause)/*end00rule*/
  }
}
