package rules.Assignment.GlobalMatterAssignmentRules_dir

@gw.rules.RuleName("GMA01000 - Default")
internal class GMA01000Default {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/Matter.CurrentAssignment.assignToIssueOwner()/*end00rule*/
  }
}
