package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPU03000 - Set SIU Life Cycle")
internal class CPU03000SetSIULifeCycle {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.SIULifeCycleState == null
      and Claim.State !="draft"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.SIULifeCycleState="step1"/*end00rule*/
  }
}
