package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPU08000 - Metro Report Request")
internal class CPU08000MetroReportRequest {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.State !="draft" &&
          libraries.Metro.hasNewMetroRequest( Claim )/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/libraries.Metro.validateAndStartReportFlows( Claim )/*end00rule*/
  }
}
