package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1120DateofLossRequirements_dir

@gw.rules.RuleName("CVXX1121 - Date of Loss is Required")
internal class CVXX1121DateofLossisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*//*

*/

claim.LossDate==Null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* This is implemented as a ERROR, because you should never have a claim without a loss date.
If the user encounters this, they can go to that field and correct it.
*/

var msg:String
msg="Please fill in the Date of Loss on the Loss Details Screen."

claim.rejectField( "LossDate", "newloss", msg,Null, Null )/*end00rule*/
  }
}
