package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1120DateofLossRequirements_dir

@gw.rules.RuleName("CVXX1122 - Date of Loss cannot be in the future")
internal class CVXX1122DateofLosscannotbeinthefuture {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*//*

*/
claim.LossDate != null and
gw.api.util.DateUtil.compareIgnoreTime( claim.LossDate, gw.api.util.DateUtil.currentDate() ) > 0/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* This is implemented as a ERROR, because you should never have a claim with afuture loss date.
If the user encounters this, they can go to that field and correct it.
*/

var msg:String
msg="Please provide a loss date that is not a future date."

if(claim.Policy.isPolicyInRefresh( 1 )){
  claim.setPolicyRefreshFailed()
}

claim.rejectField( "LossDate", "newloss", msg,Null, Null )
/*end00rule*/
  }
}
