package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05600BodilyInjuryExposure_dir

@gw.rules.RuleName("EXV05610 - Injury")
internal class EXV05610Injury {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.InjuryIncident.BodyParts.length == 0
or Exposure.InjuryIncident.FirstBodyPart.DetailedBodyPart == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if (Exposure.InjuryIncident.BodyParts.length == 0) {
  Exposure.rejectSubField( Exposure.InjuryIncident, "BodyParts", "iso", displaykey.Rules.Validation.Exposure.InjuryIncidentMustHaveBodyPartWithDetailedBodyPart, null, null )
} else {
  Exposure.rejectSubField( Exposure.InjuryIncident.FirstBodyPart, "DetailedBodyPart", "iso", displaykey.Rules.Validation.Exposure.DetailedBodyPartNotNull, null, null )
}/*end00rule*/
  }
}
