package rules.Preupdate.ContactPreupdate_dir

@gw.rules.RuleName("COPUXX1000 - All BUs Contact Pre-Update Rules")
internal class COPUXX1000AllBUsContactPreUpdateRules {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
