package rules.Validation.ClaimValidationRules_dir.CVEL1000ExecutiveLiabilityClaimValidationRules_dir.CVEL1400ValidationattheISOLevel_dir

@gw.rules.RuleName("CVEL1410 - Prevent ISO at Draft Status")
internal class CVEL1410PreventISOatDraftStatus {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.State=="draft"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "iso", " Claim cannot be in Draft status", null, null )/*end00rule*/
  }
}
