package rules.Validation.ContactValidationRules_dir.GAICValidationRules_dir.CVR1200CMS_dir

@gw.rules.RuleName("CVR1400 - ICD Codes cannot have blank row")
internal class CVR1400ICDCodescannothaveblankrow {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/contact.ContactISOMedicareExt != null and
contact.ContactISOMedicareExt.ContactICDExt.Count != 0/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*/if(contact.ContactISOMedicareExt.ContactICDExt.Count != 0){
 for(conICD in contact.ContactISOMedicareExt.ContactICDExt){ 
   if(conICD.ICDCode.Code == null){
    contact.reject("loadsave", "ICD Code: You must enter a code or remove the blank row.", null, null) 
   }
 }
}/*end00rule*/
  }
}
