package rules.Validation.ContactValidationRules_dir.GAICValidationRules_dir.CVR1200CMS_dir

@gw.rules.RuleName("CVR1220 - Exhaust Date Greater Than Date Of Incident")
internal class CVR1220ExhaustDateGreaterThanDateOfIncident {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/typeof contact == Person &&
contact.ContactISOMedicareExt != null &&
contact.ContactISOMedicareExt.ExhaustDateExt != null &&
contact.ContactISOMedicareExt.CMSIncidentDateExt != null/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*/var message = util.gaic.CMS.validation.CMSValidationExpression.exhaustDate(contact.ContactISOMedicareExt)

if(message != null){
  contact.rejectField("ContactISOMedicareExt.ExhaustDateExt", "loadsave", message, null, null) 
}/*end00rule*/
  }
}
