package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX1140VersionRequirements_dir

@gw.rules.RuleName("PVXX1141 - Version Required")
internal class PVXX1141VersionRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.ex_PolicyVersion == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "ex_PolicyVersion", "newloss", "Policy version cannot be left blank.", null, null )/*end00rule*/
  }
}
