package rules.Workplan.MatterWorkplan_dir

@gw.rules.RuleName("MWEQ1000 - Equine Matter Workplan Rules")
internal class MWEQ1000EquineMatterWorkplanRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
