package rules.Preupdate.PolicyPreupdate_dir.PPUXXPRERulesthatneedtorun_dir

@gw.rules.RuleName("PPUEQ - Equine Policy Preupdate Rules")
internal class PPUEQEquinePolicyPreupdateRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
