package rules.Preupdate.PolicyPreupdate_dir.PPUXXPRERulesthatneedtorun_dir

@gw.rules.RuleName("PPUPIM - Pim Policy PreUPdate Rules")
internal class PPUPIMPimPolicyPreUPdateRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
