package rules.Preupdate.PolicyPreupdate_dir.PPUXXPRERulesthatneedtorun_dir

@gw.rules.RuleName("PPUPSP - SpecialtyES Policy Preupdate Rules")
internal class PPUPSPSpecialtyESPolicyPreupdateRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
