package rules.Validation.MatterReopenedValidationRules_dir

@gw.rules.RuleName("MRVEQ1000 - Equine Matter Reopen Validation Rules")
internal class MRVEQ1000EquineMatterReopenValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
