package rules.Validation.MatterReopenedValidationRules_dir

@gw.rules.RuleName("MRVXX1000 - All BUs Matter Reopened Rules")
internal class MRVXX1000AllBUsMatterReopenedRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
