package rules.Preupdate.ClaimPreupdate_dir.CPUSP1000SpecialtyESClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUSP1400 - Set Medicare Flag")
internal class CPUSP1400SetMedicareFlag {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for (exp in claim.Exposures){
  exp.MedicareExposureExt = exp.isMedicareFeature(exp)
}
/*end00rule*/
  }
}
