package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir

@gw.rules.RuleName("EVXX0000 - Skip rules if closed with invalid feature")
internal class EVXX0000Skiprulesifclosedwithinvalidfeature {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Closed and exposure.ClosedOutcome == "invalidfeature"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Actions.exit()/*end00rule*/
  }
}
