package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir

@gw.rules.RuleName("EVXX2100 - Medicare Related")
internal class EVXX2100MedicareRelated {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.gaic.CMS.validation.CMSValidationUtil.generalPrecondition(exposure)
and !exposure.claim.Policy.isPolicyInRefresh( 1 )/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
