package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir

@gw.rules.RuleName("EVXX2300 - Date of Death and Beneficiary Required.")
internal class EVXX2300DateofDeathandBeneficiaryRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.New and
exposure.Claimant typeis Person and
exposure.isDateOfDeath()
/* exposure.New condition is added to invoke the warning only while creating a new feature
so that the warning is not invoked unneccesarily *//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*
Defect 6539 - jjesudhasan - 9/26/14 - Added to check the If Medicare Eligible = Yes 
and there is a Beneficiary on the Medicare tab but no Date of Death, a soft warning
has been displayed.
*/

exposure.reject(null,null, "newloss", 
"Medicare Beneficiary exists, Date of Death for claimant "+exposure.Claimant +" is required.")
/*end00rule*/
  }
}
