package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir

@gw.rules.RuleName("EVXX1200 - Ability to Pay Field Requirements")
internal class EVXX1200AbilitytoPayFieldRequirements {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
