package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir

@gw.rules.RuleName("EVXX2000 - Legal Action Related Rules")
internal class EVXX2000LegalActionRelatedRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.Matters.IsEmpty == false
      
      
      
/*
If there are legal actions on the claim this rule will run
*//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
