package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVXX1230 - Adjuster Must Be Assigned")
internal class EVXX1230AdjusterMustBeAssigned {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*this rule will check an exposure to make sure it is assigned before
  allowing to go to ability to pay
  Updated: Eric Rawe - Sprint 16: 8/15/08  (defect 1077)
*/
(exposure.Claim.AssignmentStatus!="assigned" || exposure.AssignmentStatus!="assigned")/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "payment", "There must be an assigned adjuster for the feature and claim to reach ability to pay.", null, null )/*end00rule*/
  }
}
