package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVXX1240 - Type of Loss Required")
internal class EVXX1240TypeofLossRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//* 2/27/15 - C. Mullin - Type of Loss is required at the Claim level
for Workers' Comp Claims, not at the Exposure level.  
*/
!util.WCHelper.isWCorELLossType(exposure.Claim)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
