package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVXX1210 - Claim must be at ATP")
internal class EVXX1210ClaimmustbeatATP {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///Validation for ATP must now go Policy, Claim, Feature
//Defect 2690 - sprzygocki 2/21/10
//Disabled for now since I do not have the go-ahead to commit from Karen

exposure.Claim.ValidationLevel!="payment"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "payment", "Claim must be at Ability to Pay", null, null )/*end00rule*/
  }
}
