package rules.Reopened.ClaimReopened_dir.CRXX1000AllBUClaimReopenedRules_dir

@gw.rules.RuleName("CRXX1100 - Notify external systems")
internal class CRXX1100Notifyexternalsystems {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true /* Always notify *//*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.addEvent( "claim_reopened")/*end00rule*/
  }
}
