package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir.CLV091000WorkersComp_dir

@gw.rules.RuleName("CLV091020 - Name")
internal class CLV091020Name {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.ClaimantDenorm != null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/var person = Claim.ClaimantDenorm as Person;
if( person.FirstName == null || person.FirstName.length() == 0 )
{
  Claim.rejectField( "claimant.FirstName", "iso", displaykey.Rules.Validation.Claim.ClaimantFirstNameNotEmpty, null, null )
}
if( person.LastName == null || person.LastName.length() == 0 )
{
  Claim.rejectField( "claimant.LastName", "iso", displaykey.Rules.Validation.Claim.ClaimantLastNameNotEmpty, null, null )
}/*end00rule*/
  }
}
