package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir.CLV091000WorkersComp_dir

@gw.rules.RuleName("CLV091030 - Address")
internal class CLV091030Address {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant != null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/var address = Claim.ClaimantDenorm.PrimaryAddress;
if( address.AddressLine1 == null || address.AddressLine1.length() == 0 )
{
  Claim.rejectSubField( Claim.ClaimantDenorm, "PrimaryAddress.AddressLine1", "iso", displaykey.Rules.Validation.Claim.ClaimantPrimaryAddressNotEmpty(displaykey.Term.Line1.Lower), null, null )
}

if( address.City == null || address.City.length() == 0 )
{
  Claim.rejectSubField( Claim.ClaimantDenorm, "PrimaryAddress.City", "iso", displaykey.Rules.Validation.Claim.ClaimantPrimaryAddressNotEmpty(displaykey.Term.City.Lower), null, null )
}

if( address.State == null && (address.Country == null || address.Country == Country.TC_US || address.Country == Country.TC_CA) )
{
  Claim.rejectSubField( Claim.ClaimantDenorm, "PrimaryAddress.State", "iso", displaykey.Rules.Validation.Claim.ClaimantPrimaryAddressNotEmpty(displaykey.Term.State.Lower), null, null )
}/*end00rule*/
  }
}
