package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir.CLV091000WorkersComp_dir

@gw.rules.RuleName("CLV091010 - Claimant Exists")
internal class CLV091010ClaimantExists {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.ClaimantDenorm == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "Claimant", "iso", displaykey.Rules.Validation.Claim.ClaimantNotNull, null, null )/*end00rule*/
  }
}
