package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir.CLV091000WorkersComp_dir

@gw.rules.RuleName("CLV091030 - Injury Description")
internal class CLV091030InjuryDescription {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.ClaimInjuryIncident.Description == null || Claim.ClaimInjuryIncident.Description.length() == 0/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectSubField( Claim.ClaimInjuryIncident, "Description", "iso", displaykey.Rules.Validation.Claim.ClaimantInjuryDescriptionNotEmpty, null, null )/*end00rule*/
  }
}
