package rules.Validation.GroupValidationRules_dir.GVXX1000AllBUsGroupValidationRules_dir

@gw.rules.RuleName("GVXX1100 - Current User Updates Only")
internal class GVXX1100CurrentUserUpdatesOnly {
  static function doCondition(group : entity.Group) : boolean {
    return /*start00rule*///group.UpdateUser==User.util.getCurrentUser()
// sdalal Commented out as the Updateuser returns the user who last updated the group and 
// it might not be the same as the Current user.
true/*end00rule*/
  }

  static function doAction(group : entity.Group, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
