package rules.Exception.ActivityEscalationRules_dir.AEXX1000AExclusionfilters_dir.AEXX1000AllBUActivityEscalationRules_dir

@gw.rules.RuleName("AEXX1100 - Bulk Recoveries")
internal class AEXX1100BulkRecoveries {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
