package rules.Preupdate.ExposurePreupdate_dir.EPUBS1000BondsExposurePreUpdateRules_dir

@gw.rules.RuleName("EPUBS1200 - RULES THAT CREATE ACTIVITIES")
internal class EPUBS1200RULESTHATCREATEACTIVITIES {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
