package rules.Workplan.ClaimWorkplan_dir.CLW05000Propertyclaims_dir

@gw.rules.RuleName("CLW05200 - New users")
internal class CLW05200Newusers {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignedUser.ExperienceLevel == "low"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
