package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir.TVXX1600ReserveSetRules_dir

@gw.rules.RuleName("TVXX1610 - Block Financials if Final Payment is Pending")
internal class TVXX1610BlockFinancialsifFinalPaymentisPending {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/for(trans in transactionSet.Transactions){
  
  if(trans.blockFinancials()){
    transactionSet.reject("payment", "Error: A " + trans.Subtype + " cannot be created because a final payment is pending approval.", null, null);
  }
  
}/*end00rule*/
  }
}
