package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir

@gw.rules.RuleName("PVAG1000 - AgriBusiness Policy Validation Rules")
internal class PVAG1000AgriBusinessPolicyValidationRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/Policy.Claim.LossType == "AGRIAUTO" ||
Policy.Claim.LossType == "AGRILIABILITY" ||
Policy.Claim.LossType == "AGRIPROPERTY" OR
policy.Claim.LossType == LossType.TC_ALTMARKETSAUTO OR
policy.Claim.LossType == LossType.TC_SHSAUTO OR
policy.Claim.LossType == LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
