package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir

@gw.rules.RuleName("PVEQ1000 - Equine Policy Validation Rules")
internal class PVEQ1000EquinePolicyValidationRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType=="EQUINE"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
