package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir

@gw.rules.RuleName("PVIM1000 - PIM Policy Validation Rules")
internal class PVIM1000PIMPolicyValidationRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
