package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir

@gw.rules.RuleName("PVWC1000 - Workers' Comp Policy Validation Rules")
internal class PVWC1000WorkersCompPolicyValidationRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(policy.Claim)/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
