package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir

@gw.rules.RuleName("PVXX1000 - All BUs Policy Validation Rules")
internal class PVXX1000AllBUsPolicyValidationRules {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
