package rules.Preupdate.MatterAssignmentExtPreupdate_dir

@gw.rules.RuleName("MAPUXX1000 - All BUs PreUpdate Rules")
internal class MAPUXX1000AllBUsPreUpdateRules {
  static function doCondition(matterAssignmentExt : entity.MatterAssignmentExt) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matterAssignmentExt : entity.MatterAssignmentExt, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
