package rules.Validation.ClaimValidationRules_dir.CVEL1000ExecutiveLiabilityClaimValidationRules_dir.CVEL1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVEL1310 - Detail Loss Cause 1 is Required")
internal class CVEL1310DetailLossCause1isRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.ex_DetailLossCause == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "ex_DetailLossCause", "payment", displaykey.Rules.Validation.Claim.ExecutiveLiability.DetailLossCause, null, null )/*end00rule*/
  }
}
