package rules.Validation.ClaimValidationRules_dir.CVEL1000ExecutiveLiabilityClaimValidationRules_dir.CVEL1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVEL1330 - Claim Related Type is Required")
internal class CVEL1330ClaimRelatedTypeisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType != LossType.TC_MERGACQU and
claim.ClaimRelatedTypeExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField("ClaimRelatedTypeExt", "payment", displaykey.Rules.Validation.Claim.ExecutiveLiability.ClaimRelatedType, null, null)/*end00rule*/
  }
}
