package rules.Validation.ClaimValidationRules_dir.CVEL1000ExecutiveLiabilityClaimValidationRules_dir.CVEL1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVEL1320 - Retention applies to Cost of Defense is Required")
internal class CVEL1320RetentionappliestoCostofDefenseisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.RetentionCostDefExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField("RetentionCostDefExt", "payment", displaykey.Rules.Validation.Claim.ExecutiveLiability.RetentionCostDefExt, null, null)/*end00rule*/
  }
}
