package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("EVWC1250-Medical Feature Doctor & Examination Date")
internal class EVWC1250MedicalFeatureDoctorExaminationDate {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == typekey.ExposureType.TC_WC_MEDICAL_DETAILS/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if (exposure.Claim.FirstIntakeDoctor==null){
exposure.rejectField( "claim.FirstIntakeDoctor", "payment", exposure + ": " + Displaykey.Rules.Validation.Claim.WorkersComp.Doctor, null, null )
}

if (exposure.Claim.ExaminationDate==null){
  exposure.rejectField( "claim.ExaminationDate", "payment", exposure + ": " + Displaykey.Rules.Validation.Claim.WorkersComp.ExaminationDate, null, null )

}/*end00rule*/
  }
}
