package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVWC1210 - Medical Feature ICD Code")
internal class EVWC1210MedicalFeatureICDCode {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == typekey.ExposureType.TC_WC_MEDICAL_DETAILS &&
exposure.Claim.ClaimInjuryIncident.InjuryDiagnoses.IsEmpty/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField( "Claim.MedicalTreatments", "payment", exposure + ": " + displaykey.Rules.Validation.Claim.WorkersComp.ICD, null, null )/*end00rule*/
  }
}
