package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVWC1240 - Bureau Benefit Type")
internal class EVWC1240BureauBenefitType {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == typekey.ExposureType.TC_WC_INDEMNITY_TIMELOSS &&
exposure.BureauBenefitTypeExt == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField( "BureauBenefitTypeExt", "payment", exposure + ": " + displaykey.Rules.Validation.Claim.WorkersComp.BureauBenefitType, null, null )/*end00rule*/
  }
}
