package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("EVWC1260 - Treatment Type")
internal class EVWC1260TreatmentType {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == typekey.ExposureType.TC_WC_MEDICAL_DETAILS &&
exposure.Claim.TreatmentTypeExt == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField( "Claim.TreatmentTypeExt", "payment", exposure + ": " + displaykey.Rules.Validation.Claim.WorkersComp.TreatmentType, null, null )/*end00rule*/
  }
}
