package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("EVWC1230-Validate Beneficiary DOB,Dependncy & Reltnship code")
internal class EVWC1230ValidateBeneficiaryDOBDependncyReltnshipcode {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///Added below validation rule functions to ensure the  Beneficiary Date of Birth, Beneficiary Dependency code and Beneficiary Relationship code
//are not Null at Ability to pay validation level
//Developer:Asaikumar Date:06/09/2015  
//11.11.15 - Defect 7750 - Beneficiary validation removed. Rule disabled.
true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/libraries.Exposure_Entity.ExposureFunctions.BenDateOfBirthVal(exposure)
libraries.Exposure_Entity.ExposureFunctions.BeneficiaryDepndVal(exposure)
libraries.Exposure_Entity.ExposureFunctions.BeneficiaryRelatnVal(exposure)/*end00rule*/
  }
}
