package rules.Validation.ExposureValidationRules_dir.EVWC1000WorkersCompExposureValidationRules_dir.EVWC1200AbilitytoPayFieldRequirements_dir

@gw.rules.RuleName("EVWC1270 - Average Weekly Wage")
internal class EVWC1270AverageWeeklyWage {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == typekey.ExposureType.TC_WC_INDEMNITY_TIMELOSS &&
exposure.Claim.EmploymentData.WageAmount == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField( "Claim.EmploymentData.WageAmount", "payment", exposure + ": " + displaykey.Rules.Validation.Claim.WorkersComp.AverageWeeklyWage, null, null )/*end00rule*/
  }
}
