package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1300ValidforISO_dir

@gw.rules.RuleName("PVXX1310 - Insured")
internal class PVXX1310Insured {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.isPolicyInRefresh( 0 )==true  //only run when the policy is not in refresh mode
                                //first cycle of policy validation contact is null although
                                //it does exist, and is checked on second cycle./*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
