package rules.Validation.ClaimValidationRules_dir.CLV12000Injurydiagnosisvaliditydates_dir

@gw.rules.RuleName("CLV120100 - WC")
internal class CLV120100WC {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "WC"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for(eachDiagnosis in claim.ClaimInjuryIncident.InjuryDiagnoses) {
  if(!eachDiagnosis.startDateBetweenCodeValidity()) {
    claim.reject(null, null, "iso", eachDiagnosis.diagnosisCodeWarningString())
  }
  if(!eachDiagnosis.endDateBetweenCodeValidity()){
    claim.reject(null, null, "iso", eachDiagnosis.diagnosisCodeWarningString())  
  } 
}/*end00rule*/
  }
}
