package rules.Postsetup.ActivityPostsetup_dir

@gw.rules.RuleName("APOEQ1000 - Equine Post-Setup Rules")
internal class APOEQ1000EquinePostSetupRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
