package rules.Postsetup.ActivityPostsetup_dir

@gw.rules.RuleName("APOIM1000 - PIM Activity Post-Setup Rules")
internal class APOIM1000PIMActivityPostSetupRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
