package rules.Postsetup.ActivityPostsetup_dir

@gw.rules.RuleName("APOXX1000 - All BUs Activity PostSetup Rules")
internal class APOXX1000AllBUsActivityPostSetupRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*///Rules for all LOBs
true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
