package rules.BulkInvoiceApproval.BulkInvoiceApprovalRules_dir

@gw.rules.RuleName("BIAXX1000 - All BU Bulk Invoice Approval Rules")
internal class BIAXX1000AllBUBulkInvoiceApprovalRules {
  static function doCondition(bulkInvoice : entity.BulkInvoice) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(bulkInvoice : entity.BulkInvoice, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
