package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Cash Receipt Form")
internal class CashReceiptForm {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Recovery && messageContext.DestID == 3/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
/*end00rule*/
  }
}
