package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("CatastropheEvents")
internal class CatastropheEvents {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Catastrophe ||
messageContext.Root typeis Ex_CatOccurance/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
