package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 5 - Independent Adjusters")
internal class Destination5IndependentAdjusters {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 5/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
