package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 17 - Group User Export")
internal class Destination17GroupUserExport {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 17/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
