package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 4 - Check Print")
internal class Destination4CheckPrint {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 4/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
