package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 6 - LitAdvisor")
internal class Destination6LitAdvisor {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 6 && 
util.admin.ExternalUserAdminUtil.isLitAdvisorEnabled(messageContext)/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
