package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 8 - Taxport 1099")
internal class Destination8Taxport1099 {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 8/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
