package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 11 - LDM")
internal class Destination11LDM {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 11
/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
