package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 14 - Claim Export")
internal class Destination14ClaimExport {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 14 &&
util.admin.ExternalUserAdminUtil.isMedVendorEnabled(messageContext)/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
