package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 7 - OFAC")
internal class Destination7OFAC {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 7/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
