package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 10 - LDM")
internal class Destination10LDM {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 10/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
