package rules.EventMessage.EventFired_dir

@gw.rules.RuleName("Destination 9 - Escheatment")
internal class Destination9Escheatment {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.DestID == 9/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
