package rules.Preupdate.TransactionSetPreupdate_dir.TPUXX1000AllBUTransactionPreUpdate_dir.TPUXX1200CheckSet_dir

@gw.rules.RuleName("TPUXX12C0 - LitAdvisor Checks")
internal class TPUXX12C0LitAdvisorChecks {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/(transactionSet as CheckSet).PrimaryCheck != null &&
(transactionSet as CheckSet).PrimaryCheck.CheckCategoryExt == CheckCategoryExt.TC_LIT_ADVISOR/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
