package rules.Presetup.MatterPresetup_dir

@gw.rules.RuleName("MPREQ1000 - Equine Matter Pre Setup Rules")
internal class MPREQ1000EquineMatterPreSetupRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
