package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVAG1000 - Agribusiness Exposure Closed Validation Rules")
internal class ECVAG1000AgribusinessExposureClosedValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == "AGRIAUTO" ||
exposure.Claim.LossType == "AGRILIABILITY" ||
exposure.Claim.LossType == "AGRIPROPERTY" OR 
exposure.Claim.LossType==LossType.TC_ALTMARKETSAUTO OR 
exposure.Claim.LossType==LossType.TC_SHSAUTO OR 
exposure.Claim.LossType==LossType.TC_TRUCKINGAUTO/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
