package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVEQ1000 - Equine Exposure Closed Validation Rules")
internal class ECVEQ1000EquineExposureClosedValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
