package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVSP1000 - Specialty E&S Exposure Closed Validation Rules")
internal class ECVSP1000SpecialtyESExposureClosedValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
