package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVWC1000 - Workers' Comp Exposure Closed Validation Rules")
internal class ECVWC1000WorkersCompExposureClosedValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(exposure.Claim)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
