package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVXX1000 - All BU Exposure Closed Validation Rules")
internal class ECVXX1000AllBUExposureClosedValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
