package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir

@gw.rules.RuleName("TVXX1700 - Validate Authority")
internal class TVXX1700ValidateAuthority {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/!exists(trans in transactionSet.Transactions where trans.Subtype == "payment" and 
  ((trans as Payment).Recoded or (trans as Payment).Check.Transferred or 
   (trans as Payment).Check.TransferredCheck != null)) and
transactionSet.Changed/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
