package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir

@gw.rules.RuleName("TVXX1100 - CheckSet Rules")
internal class TVXX1100CheckSetRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Subtype =="CheckSet" &&
!(transactionSet as CheckSet).ForBulkedCheck/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
