package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir

@gw.rules.RuleName("TVXX1400 - Checkset Rules (Not Transferred Check)")
internal class TVXX1400ChecksetRulesNotTransferredCheck {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Subtype =="CheckSet" and
  exists (check in (transactionSet as CheckSet).Checks where check.Transferred == false and check.TransferredCheck == null)
  &&
!(transactionSet as CheckSet).ForBulkedCheck/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
