package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("TVXX2200 - Mailing address validation")
internal class TVXX2200Mailingaddressvalidation {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*//* 
  Defect: 7527
  Comments: Disable the following Warning Message from generating, for all scenarios: 
  'Verify Check is to be sent to Mailing Address as shown.' 
*/
transactionSet.Subtype == "CheckSet" and
(transactionSet as CheckSet).PrimaryCheck.DeliveryMethod=="hold" and
(transactionSet as CheckSet).PrimaryCheck.ex_MailToAddress.AddressType=="mailing"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/transactionSet.reject(null,null,"payment",displaykey.Validation.Financials.NewCheckPayee.Check.MailingAddress)

  /*end00rule*/
  }
}
