package rules.Validation.TransactionSetValidationRules_dir.TVXX1000AllBUsTransactionValidationRules_dir

@gw.rules.RuleName("TVXX1200 - ReserveSet & RecoverySet Rules")
internal class TVXX1200ReserveSetRecoverySetRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/(transactionSet.Subtype =="ReserveSet" || 
transactionSet.Subtype =="RecoveryReserveSet" ||
transactionSet.Subtype =="RecoverySet")
/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
