package rules.Preupdate.ActivityPreupdate_dir.APUAC1000ACLsActivityPreUpdateRules_dir.APUAC1100TempAccesstoSecureClaim_dir

@gw.rules.RuleName("APUAC9999 - Rebuild Claim ACL")
internal class APUAC9999RebuildClaimACL {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*/activity.Claim.rebuildClaimACL()/*end00rule*/
  }
}
