package rules.Preupdate.TransactionSetPreupdate_dir.TPUXX1000AllBUTransactionPreUpdate_dir.TPUXX1200CheckSet_dir.TPUXX1240TransferCheck_dir

@gw.rules.RuleName("TPUXX1243- Copy Escheat Status")
internal class TPUXX1243CopyEscheatStatus {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/for(check in (transactionSet as CheckSet).Checks){
  check.TransferredToCheck.EscheatStatusExt = check.EscheatStatusExt;
}/*end00rule*/
  }
}
