package rules.EventMessage.EventFired_dir.Destination3EDW_dir

@gw.rules.RuleName("Association")
internal class Association {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis ClaimAssociation == true
/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
