package rules.EventMessage.EventFired_dir.Destination3EDW_dir

@gw.rules.RuleName("Catastrophe")
internal class Catastrophe {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Catastrophe == true/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
