package rules.EventMessage.EventFired_dir.Destination3EDW_dir

@gw.rules.RuleName("CatOccurance")
internal class CatOccurance {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Ex_CatOccurance == true/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
