package rules.EventMessage.EventFired_dir.Destination3EDW_dir

@gw.rules.RuleName("Payment")
internal class Payment {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis Payment
&& messageContext.Root.Check.Claim.State != "draft"
/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
