package rules.Reopened.ExposureReopened_dir

@gw.rules.RuleName("EREQ1000 - Equine Exposure Reopened Rules")
internal class EREQ1000EquineExposureReopenedRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
