package rules.Preupdate.UserPreupdate_dir.UPUXX1000AllBUsUserPreUpdateRules_dir

@gw.rules.RuleName("UPUXX1200 -Set Employee ID")
internal class UPUXX1200SetEmployeeID {
  static function doCondition(user : entity.User) : boolean {
    return /*start00rule*/user.Contact.EmployeeNumber == null/*end00rule*/
  }

  static function doAction(user : entity.User, actions : gw.rules.Action) {
/*start00rule*/user.Contact.EmployeeNumber = user.Credential.UserName/*end00rule*/
  }
}
