package rules.Preupdate.UserPreupdate_dir.UPUXX1000AllBUsUserPreUpdateRules_dir

@gw.rules.RuleName("UPUXXZZZZ - Corp Accounts")
internal class UPUXXZZZZCorpAccounts {
  static function doCondition(user : entity.User) : boolean {
    return /*start00rule*/true

/*end00rule*/
  }

  static function doAction(user : entity.User, actions : gw.rules.Action) {
/*start00rule*/util.admin.SecurityUtil.updateAllClaimsForUserChange(user)
/*end00rule*/
  }
}
