package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("Exit On Converted Claims")
internal class ExitOnConvertedClaims {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/!transactionSet.Claim.isNativeORUpdatedExt() &&
transactionSet.LoadCommandID!=null/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*/actions.exit();/*end00rule*/
  }
}
