package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVAG1000 - AgriBusiness Transaction Validation Rules")
internal class TVAG1000AgriBusinessTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/(transactionSet.Claim.LossType =="AGRIAUTO" ||
transactionSet.Claim.LossType=="AGRILIABILITY" ||
transactionSet.Claim.LossType=="AGRIPROPERTY" OR
transactionSet.Claim.LossType==LossType.TC_ALTMARKETSAUTO OR
transactionSet.Claim.LossType==LossType.TC_SHSAUTO OR
transactionSet.Claim.LossType==LossType.TC_TRUCKINGAUTO) and 
transactionSet.Claim.Policy.isPolicyInRefresh( 0 )/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
