package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVAM1000 - Alt Markets Transaction Validation Rules")
internal class TVAM1000AltMarketsTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType == LossType.TC_ALTMARKETSAUTO or
transactionSet.Claim.LossType == LossType.TC_ALTMARKETSWC or 
transactionSet.Claim.LossType == LossType.TC_ALTMARKETSEL/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
