package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVBS1000 - Bonds Transaction Validation Rules")
internal class TVBS1000BondsTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType==LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
