package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVEQ1000 - Equine Transaction Validation Rules")
internal class TVEQ1000EquineTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType == "EQUINE" and
transactionSet.Claim.Policy.isPolicyInRefresh( 0 )
 /*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//* Run Child Rules *//*end00rule*/
  }
}
