package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVIM1000 - PIM Transaction Validation Rules")
internal class TVIM1000PIMTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
