package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVOM1000 - Ocean Marine Transaction Validation Rules")
internal class TVOM1000OceanMarineTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType==LossType.TC_OMAVALON/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
