package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVWC1000 - Workers Comp Transaction Validation Rules")
internal class TVWC1000WorkersCompTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(transactionSet.Claim)/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
