package rules.Validation.TransactionSetValidationRules_dir

@gw.rules.RuleName("TVXX1000 - All BUs Transaction Validation Rules")
internal class TVXX1000AllBUsTransactionValidationRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.Policy.isPolicyInRefresh( 0 )==true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
