package rules.Validation.ClaimValidationRules_dir.CVPL1000ProfessionalLiabilityClaimValidationRules_dir.CVEL1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVEL1310 - Loss Cause is Required")
internal class CVEL1310LossCauseisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossCause == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "ClaimTypeLossCauseExt", "payment", displaykey.Rules.Validation.Claim.ProfessionalLiability.LossCause, null, null )/*end00rule*/
  }
}
