package rules.Validation.ClaimValidationRules_dir.CVPL1000ProfessionalLiabilityClaimValidationRules_dir.CVEL1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVEL1330 - Claim Type is Required")
internal class CVEL1330ClaimTypeisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ClaimTypeExt == null /*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField("ClaimTypeExt", "payment", displaykey.Rules.Validation.Claim.ProfessionalLiability.ClaimType, null, null)/*end00rule*/
  }
}
