package rules.EventMessage.EventFired_dir.Destination4CheckPrint_dir

@gw.rules.RuleName("BulkInvoice")
internal class BulkInvoice {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis BulkInvoice == true/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
