package rules.Segmentation.ClaimSegmentationRules_dir

@gw.rules.RuleName("CSEQ1000 - Equine Claim Segmentation Rules")
internal class CSEQ1000EquineClaimSegmentationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
