package rules.Segmentation.ClaimSegmentationRules_dir

@gw.rules.RuleName("CSXX1000 - All BUs Claim Segmentation Rules")
internal class CSXX1000AllBUsClaimSegmentationRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
