package rules.Validation.ContactValidationRules_dir.GAICValidationRules_dir

@gw.rules.RuleName("CVR1500 -  Warn if primary Email Address is missing")
internal class CVR1500WarnifprimaryEmailAddressismissing {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/(contact.Subtype == "CompanyVendor" or 
contact.Subtype == "PersonVendor" or 
contact.Subtype == "Attorney" or  
contact.Subtype == "Doctor" or 
contact.Subtype == "Ex_GAIVendor" or
contact.Subtype == "LawFirm" or 
contact.Subtype == "MedicalCareOrg" or
contact.Subtype == "Ex_ForeignCoVendor" or 
contact.Subtype == "Ex_ForeignCoVenMedOrg" or 
contact.Subtype == "Ex_ForeignCoVenLawFrm" or 
contact.Subtype == "Ex_ForeignPersonVndr" or
contact.Subtype == "Ex_ForeignPerVndrAttny" or
contact.Subtype == "Ex_ForeignPerVndrDoc" or
contact.Subtype == "FrgnAutoRepairShopExt" or
contact.Subtype == "AutoRepairShop") && 
contact.EmailAddress1==null &&
!(contact.generateLinkStatus().LinkStatusValue=="synced" or contact.generateLinkStatus().LinkStatusValue=="notsynced" )
/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*/contact.reject(null, null, "loadsave", "The Main Email address has not been entered for this Vendor.  If the Main Email address is available, enter it at this time.")/*end00rule*/
  }
}
