package rules.Validation.ContactValidationRules_dir.GAICValidationRules_dir

@gw.rules.RuleName("CVR1800 - Do Not Allow Contacts to Exceed 20 MailingAddress")
internal class CVR1800DoNotAllowContactstoExceed20MailingAddress {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/contact.AllAddresses.where(\ a -> a.AddressType == AddressType.TC_MAILING ).length > 20/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*/contact.reject("loadsave", "The number of mailing addresses exceeds 20. Additional mailing addresses may be added to the contact on the Related Contacts tab in Address Book.", null, null)/*end00rule*/
  }
}
