package rules.Validation.ContactValidationRules_dir.GAICValidationRules_dir

@gw.rules.RuleName("CVR1600 - Closed Venders Not Valid")
internal class CVR1600ClosedVendersNotValid {
  static function doCondition(contact : entity.Contact) : boolean {
    return /*start00rule*/contact.New and 
contact.CloseDateExt != null and
contact.LoadCommandID != ScriptParameters.CurrentConversionLoadCommandID and
contact.LoadCommandID != ScriptParameters.GOSULoadCommandID
/*end00rule*/
  }

  static function doAction(contact : entity.Contact, actions : gw.rules.Action) {
/*start00rule*/

contact.reject("loadsave", contact.DisplayName + ": This Vendor is Closed. Select a valid Vendor.", null, null)/*end00rule*/
  }
}
