package rules.TransactionApproval.TransactionApprovalRules_dir

@gw.rules.RuleName("TAEQ1000 - Equine Transaction Approval Rules")
internal class TAEQ1000EquineTransactionApprovalRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
