package rules.TransactionApproval.TransactionApprovalRules_dir

@gw.rules.RuleName("TAXX1000 - All BUs Transaction Approval Rules")
internal class TAXX1000AllBUsTransactionApprovalRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
