package rules.Validation.MatterAssignmentExtValidationRules_dir

@gw.rules.RuleName("MAVXX1000 - Counsel Address")
internal class MAVXX1000CounselAddress {
  static function doCondition(matterAssignmentExt : entity.MatterAssignmentExt) : boolean {
    return /*start00rule*/matterAssignmentExt.CounselContactAddressExt == null
/*end00rule*/
  }

  static function doAction(matterAssignmentExt : entity.MatterAssignmentExt, actions : gw.rules.Action) {
/*start00rule*/var msg:String
try{

if (matterAssignmentExt.CounselContactAddressExt == null) {
     msg="Counsel Law Firm must have Contact Address."
    matterAssignmentExt.rejectField( "CounselContactAddressExt", "newloss", msg,Null, Null )
  }
  
    } catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( matterAssignmentExt, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
