package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1100NewLossFieldRequirements_dir

@gw.rules.RuleName("EVXX1130 - In Suit Required")
internal class EVXX1130InSuitRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*Requires In Suit Indicator at the new loss level.
  Sprint/Maintenance Release: Sprint 16
  Author: Zach Thomas
  Date: 9/30/08
*/
exposure.ex_InSuit == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  if(exposure.ex_InSuit == null){
    exposure.rejectField( "ex_InSuit", "newloss", displaykey.Rules.Validation.Exposure.Enterprise.Exposure.InSuit, null, null ) ;
  }
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( exposure, actions.getRule() as java.lang.String, e, null )
}  /*end00rule*/
  }
}
