package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1100NewLossFieldRequirements_dir

@gw.rules.RuleName("EVXX1160 - Claimant Required")
internal class EVXX1160ClaimantRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claimant == null /*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/if(exposure.Claimant == null){
   exposure.rejectField( "Claimant", "newloss", "Claimant name must not be blank.", null, null ) ;
}/*end00rule*/
  }
}
