package rules.Validation.MatterValidationRules_dir

@gw.rules.RuleName("MVAG1000 - AgriBusiness Matter Validation Rules")
internal class MVAG1000AgriBusinessMatterValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/Matter.Claim.LossType == "AGRIAUTO" ||
Matter.Claim.LossType == "AGRILIABILITY" ||
Matter.Claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
