package rules.Validation.MatterValidationRules_dir

@gw.rules.RuleName("MVEQ1000 - Equine Matter Validation Rules")
internal class MVEQ1000EquineMatterValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
