package rules.Validation.MatterValidationRules_dir

@gw.rules.RuleName("MVXX1000 - All BUs Matter Validation Rules")
internal class MVXX1000AllBUsMatterValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
