package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir

@gw.rules.RuleName("CVXX1200 - Validation at the ISO Level")
internal class CVXX1200ValidationattheISOLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ISOEnabled==true or
claim.LossType==typekey.LossType.TC_EXCESSLIABILITY or 
claim.LossType==typekey.LossType.TC_EXCESSLIABILITYAUTO or 
claim.LossType==typekey.LossType.TC_SPECIALTYES/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/// Exec children/*end00rule*/
  }
}
