package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EXW02000 - Auto exposure")
internal class EXW02000Autoexposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType == "vehicledamage" && !exposure.Claim.FirstAndFinal/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
