package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EXW06000 - WC Lost Wages Exposure")
internal class EXW06000WCLostWagesExposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType =="lostwages"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
