package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EXW05000 - WC Injury Exposure")
internal class EXW05000WCInjuryExposure {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.ExposureType =="wcinjurydamage"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* execute child rules *//*end00rule*/
  }
}
