package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EXW07000 -  Homeowners Policy")
internal class EXW07000HomeownersPolicy {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.Policy.PolicyType == "homeowners"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
