package rules.Validation.ClaimValidationRules_dir.CLV09000ISOValidation_dir.CLV09900Insured_dir

@gw.rules.RuleName("CLV09910 - Insured Exists")
internal class CLV09910InsuredExists {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/Claim.InsuredDenorm == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.rejectField( "Insured", "iso", displaykey.Rules.Validation.Claim.InsuredNotNull, null, null ) /*end00rule*/
  }
}
