package rules.Validation.ExposureValidationRules_dir.EVISO000ISOExposureValidationRules_dir.EVISO100GeneralRequirements_dir

@gw.rules.RuleName("EVISO110 - Claim/Policy must be at ISO Level")
internal class EVISO110ClaimPolicymustbeatISOLevel {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///So that we don't have to add duplicate rules to the exposure ruleset for all the
//claim and policy fields required for 
(exposure.Claim.ValidationLevel=="loadsave" || 
 exposure.Claim.ValidationLevel=="newloss") ||
(exposure.Claim.Policy.ValidationLevel=="loadsave" || 
 exposure.Claim.Policy.ValidationLevel=="newloss")/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var msg = "The Claim and Policy must meet the requirements to send to ISO before the Feature can be sent."

exposure.reject( "iso", msg, null, null )/*end00rule*/
  }
}
