package rules.Validation.ExposureClosedValidationRules_dir.ECVWC1000WorkersCompExposureClosedValidationRules_dir

@gw.rules.RuleName("ECVWC1200 - Prevent Close with Conversion ICD")
internal class ECVWC1200PreventClosewithConversionICD {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/util.WCHelper.isWCLossType(exposure.Claim) &&
exposure.InjuryIncident != null &&
exposure.LoadCommandID != ScriptParameters.CurrentConversionLoadCommandID &&
exposure.LoadCommandID != ScriptParameters.GOSULoadCommandID &&
exposure.InjuryIncident.InjuryDiagnoses.HasElements

/**
 * Defect 8650: If the one and only ICD code is 'WCCONV', then do not allow the feature to be closed.
 *//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/var inc = exposure.InjuryIncident
if(inc.InjuryDiagnoses.Count == 1 && inc.InjuryDiagnoses.first().ICDCode.Code == gw.api.iso.ISOInjuryLossSection._WCICD){
  exposure.reject(ValidationLevel.TC_NEWLOSS, displaykey.InjuryIncident.ConversionICDClose(gw.api.iso.ISOInjuryLossSection._WCICD), null, null)
}/*end00rule*/
  }
}
