package rules.Reopened.ClaimReopened_dir

@gw.rules.RuleName("CRAG1000 - AgriBusiness Claim Reopened Rules")
internal class CRAG1000AgriBusinessClaimReopenedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AGRIAUTO" ||
claim.LossType == "AGRILIABILITY" ||
claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
