package rules.Reopened.ClaimReopened_dir

@gw.rules.RuleName("CREQ1000 - Equine Claim Reopened Rules")
internal class CREQ1000EquineClaimReopenedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
