package rules.Reopened.ClaimReopened_dir

@gw.rules.RuleName("CRXX2000 - Claims Conversion All BU Claim Reopened Rules")
internal class CRXX2000ClaimsConversionAllBUClaimReopenedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/!claim.isNativeORUpdatedExt() == true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.ReOpenDate = null
claim.ReopenedReason = null/*end00rule*/
  }
}
