package rules.Reopened.ClaimReopened_dir

@gw.rules.RuleName("CRXX1000 - All BU Claim Reopened Rules")
internal class CRXX1000AllBUClaimReopenedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.isNativeORUpdatedExt() == true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
