package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir

@gw.rules.RuleName("EXV05710 - Vehicle")
internal class EXV05710Vehicle {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.VehicleIncident.Vehicle == null ||
Exposure.VehicleIncident.Vehicle.Year == null ||
(Exposure.VehicleIncident.Vehicle.Make == null && Exposure.VehicleIncident.Vehicle.Manufacturer == null)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.VehicleMustHaveYearAndMake, null, null )/*end00rule*/
  }
}
