package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir

@gw.rules.RuleName("EXV05730 - Off Road Vehicle")
internal class EXV05730OffRoadVehicle {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.VehicleIncident.Vehicle != null
&& (Exposure.VehicleIncident.Vehicle.Style =="ATV"
    || Exposure.VehicleIncident.Vehicle.Style == "snowmobile")/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
