package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir

@gw.rules.RuleName("EXV05720 - Normal Vehicle")
internal class EXV05720NormalVehicle {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.VehicleIncident.Vehicle != null
&& Exposure.VehicleIncident.Vehicle.Style !="ATV"
&& Exposure.VehicleIncident.Vehicle.Style !="snowmobile"
&& Exposure.VehicleIncident.Vehicle.Style !="boat"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
