package rules.Validation.ExposureValidationRules_dir.EVXX1000ALLBUsExposureValidationRules_dir.EVXX1200AbilitytoPayFieldRequirements_dir.EVXX1270MinorChild_dir

@gw.rules.RuleName("EVXX1271 - Minor Child Required")
internal class EVXX1271MinorChildRequired {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.isMinorChildFeature()
and exposure.MinorChildExt==null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "payment", "Minor Child cannot be null", null, null ) /*end00rule*/
  }
}
