package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1230 - Year of Aircraft is Required")
internal class CVXX1230YearofAircraftisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AircraftYearExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "AircraftYearExt", "payment", displaykey.Rules.Validation.Claim.Aviation.Year, null, null )/*end00rule*/
  }
}
