package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1220 - Model is Required")
internal class CVXX1220ModelisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AircraftModelExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "AircraftModelExt", "payment", displaykey.Rules.Validation.Claim.Aviation.Model, null, null )/*end00rule*/
  }
}
