package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1250 - Standard Airworthiness Certificate is Required")
internal class CVXX1250StandardAirworthinessCertificateisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.StandardAirworthinessExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "StandardAirworthinessExt", "payment", displaykey.Rules.Validation.Claim.Aviation.SAC, null, null )/*end00rule*/
  }
}
