package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1240 - Tail Number is Required")
internal class CVXX1240TailNumberisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.TailNumberExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "TailNumberExt", "payment", displaykey.Rules.Validation.Claim.Aviation.TailNum, null, null )/*end00rule*/
  }
}
