package rules.Validation.ClaimValidationRules_dir.CVAV1000AviationClaimValidationRules_dir.CVXX1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVXX1210 - Make is Required")
internal class CVXX1210MakeisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AircraftMakeExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "AircraftMakeExt", "payment", displaykey.Rules.Validation.Claim.Aviation.Make, null, null )/*end00rule*/
  }
}
