package rules.Validation.ExposureValidationRules_dir.EVAG1000AgriBusinessExposureValidationRules_dir.EVAG1300ValidforAbilitytoPay_dir

@gw.rules.RuleName("EVAG1350 - SchedPersProp Feature Detail")
internal class EVAG1350SchedPersPropFeatureDetail {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.PrimaryCoverage == "ab_SCPROP_camera" || exposure.PrimaryCoverage == "ab_SCPROP_coins" ||
exposure.PrimaryCoverage == "ab_SCPROP_finearte" || exposure.PrimaryCoverage == "ab_SCPROP_finearti" ||
exposure.PrimaryCoverage == "ab_SCPROP_furs" || exposure.PrimaryCoverage == "ab_SCPROP_golfequip" ||
exposure.PrimaryCoverage == "ab_SCPROP_guns" || exposure.PrimaryCoverage == "ab_SCPROP_jewelry" ||
exposure.PrimaryCoverage == "ab_SCPROP_miscperprp" || exposure.PrimaryCoverage == "ab_SCPROP_musicinst" ||
exposure.PrimaryCoverage == "ab_SCPROP_silverware" || exposure.PrimaryCoverage == "ab_SCPROP_sportequip" ||
exposure.PrimaryCoverage == "ab_SCPROP_stamps"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  if(exposure.ExposureDetailsExt == null){
    exposure.reject( "payment", displaykey.Rules.Validation.Exposure.AgriBusiness.AbilityToPay.ExposureDetailsExt(displaykey.NVV.Exposure.SubView.ExposureInformation.Exposure.FeatureAttributes(exposure.ExposureType)), null, null );
  }
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( exposure, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
