package rules.Validation.ExposureValidationRules_dir.EVAG1000AgriBusinessExposureValidationRules_dir.EVAG1300ValidforAbilitytoPay_dir

@gw.rules.RuleName("EVAG1340 - Course of Employment")
internal class EVAG1340CourseofEmployment {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*///***Removed extra feature types from validation as this field
//does not apply to boat, engine or trailer***
//sprzygocki 4/1/08
exposure.ExposureType == "ab_PhysicalDamage"
&& exposure.CourseOfEmployExt == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "payment", "'In Course of Employment' question on feature cannot be null. ", null, null )
  /*end00rule*/
  }
}
