package rules.Validation.ExposureValidationRules_dir.EVAG1000AgriBusinessExposureValidationRules_dir.EVAG1300ValidforAbilitytoPay_dir

@gw.rules.RuleName("EVAG1360 - Salvage Potential")
internal class EVAG1360SalvagePotential {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*Check Salvage potential only if a property feature
  Sprint: ? 
  Author: ?
  Date: ?
  Updated: 5/9/08 - Eric Rawe - Added all/only property features in the condition
*/
true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  if((exposure.ExposureType == "ab_FarmStructure" || exposure.ExposureType == "ab_BlanketFarmPerProp" ||
             exposure.ExposureType == "ab_SchedFarmPerProp" || exposure.ExposureType == "ab_IdentityTheft" ||
             exposure.ExposureType == "ab_Dwelling" || exposure.ExposureType == "ab_App_Priv_Struc" ||
             exposure.ExposureType == "ab_House_Per_Prop" || exposure.ExposureType == "ab_Loss_of_Use" ||
             exposure.ExposureType == "ab_Buy_Up" || exposure.ExposureType == "ab_Equip_Brkdwn" ||
             exposure.ExposureType == "ab_Loss_of_Farm_Inc" || exposure.ExposureType == "ab_SchedPerProp" ||
             exposure.ExposureType == "ab_BoatDamage" || exposure.ExposureType == "ab_EngineDamage" ||
             exposure.ExposureType == "ab_PropertyDamage" || exposure.ExposureType == "ab_Ext_Expense" ||
             exposure.ExposureType ==  "ab_AGG_auto_PropDamage" || exposure.ExposureType == "ab_AGG_gl_PropDamage"|| exposure.ExposureType == "ab_PhysicalDamage" ||
             exposure.ExposureType == "ab_TrailerDamage" || exposure.ExposureType == "ab_AutoPropDam")&&
  exposure.SalvagePotentialExt == null)
  {
    exposure.rejectField( "SalvagePotentialExt", "payment", "An answer is needed on the salvage potential question to be at Ability to Pay.", null, null )
  }
}
catch(e)
{
    gw.api.util.Logger.logError( "Unknown Error Occurred in Exposure Validation Rules "+actions.getRule().DisplayName)  
}/*end00rule*/
  }
}
