package rules.Validation.ExposureValidationRules_dir.EVIM1000PIMExposureValidationRules_dir.EVIM1100NewLossValidation_dir

@gw.rules.RuleName("EVIM1110 - Reserved File")
internal class EVIM1110ReservedFile {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LevelOfReserveExt==null
/*
erawe
3/2/12
Defect 5105
Note: comments below code so you can debug without removing comments.
*//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  exposure.reject("newloss", displaykey.Rules.Validation.Claim.PIM.LevelOfReserve, null, null )
} catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( exposure, actions.getRule().DisplayName, e, null )
}
/*end00rule*/
  }
}
