package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECV06000 - Loss of Use-specific checks")
internal class ECV06000LossofUsespecificchecks {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ExposureType=="lossofusedamage"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* Child rules, if any, will be specific checks for loss of use exposures *//*end00rule*/
  }
}
