package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECV04000 - Property-specific checks")
internal class ECV04000Propertyspecificchecks {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ExposureType=="propertydamage"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* Child rules, if any, will be specific checks for property exposures *//*end00rule*/
  }
}
