package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECV05000 - Contents-specific checks")
internal class ECV05000Contentsspecificchecks {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.ExposureType=="personalpropertydamage"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* Child rules, if any, will be specific checks for contents losses *//*end00rule*/
  }
}
