package rules.Validation.ExposureClosedValidationRules_dir

@gw.rules.RuleName("ECV01000 - Open activities")
internal class ECV01000Openactivities {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exists(activity in exposure.Claim.Activities
  where (activity.Exposure == exposure and
        activity.Status == "open" and
        activity.ActivityPattern != null and
        not activity.ActivityPattern.ClosedClaimAvlble)
)/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "newloss", displaykey.Rules.Validation.Exposure.CompleteOpenActivities, null, null )/*end00rule*/
  }
}
