package rules.Preupdate.PolicyPreupdate_dir.PPUXXPRERulesthatneedtorun_dir.PPUXXABUAllBussinesUnit_dir

@gw.rules.RuleName("PPUXX2000 - Default Underwriter")
internal class PPUXX2000DefaultUnderwriter {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.isPolicyInRefresh( 1 )/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.Claim.setDefaultUnderwriter()/*end00rule*/
  }
}
