package rules.Postsetup.TransactionSetPostsetup_dir

@gw.rules.RuleName("TPOIM1000 - PIM Transaction PostSetup Rules")
internal class TPOIM1000PIMTransactionPostSetupRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/transactionSet.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
