package rules.Postsetup.TransactionSetPostsetup_dir

@gw.rules.RuleName("TPOXX1000 - All BU Transaction PostSetup Rules")
internal class TPOXX1000AllBUTransactionPostSetupRules {
  static function doCondition(transactionSet : entity.TransactionSet) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(transactionSet : entity.TransactionSet, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
