package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX1130ModRequirements_dir

@gw.rules.RuleName("PVXX1131 - Mod Required")
internal class PVXX1131ModRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
policy.PolicySuffix == null/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "PolicySuffix", "newloss", "Policy mod cannot be left blank.", null, null )/*end00rule*/
  }
}
