package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1140Insured_dir

@gw.rules.RuleName("CVXX1141 - Insured Exists")
internal class CVXX1141InsuredExists {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Insured == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "Insured", "newloss", "The claim's insured must not be null", null, null )/*end00rule*/
  }
}
