package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1100ValidationatNewLossLevel_dir.CVXX1140Insured_dir

@gw.rules.RuleName("CVXX1142 - Insured Name Required")
internal class CVXX1142InsuredNameRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Insured.DisplayName == null

/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/
claim.rejectField( "Insured.Name", "newloss", "Insured must have a name.", null, null )
/*end00rule*/
  }
}
