package rules.Validation.MatterClosedValidationRules_dir.MCVXX1000AllBUsMatterClosedValidationRules_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("MCVXX1100 - Close Before Trial")
internal class MCVXX1100CloseBeforeTrial {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/gw.api.util.DateUtil.compareIgnoreTime(matter.TrialDate,gw.api.util.DateUtil.currentDate())>0/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/// This is a test rule, introduced to test validation warnings in close validation rules
matter.reject( null, null, "newloss", "Closing matter before reaching trial date" )/*end00rule*/
  }
}
