package rules.Validation.MatterClosedValidationRules_dir.MCVXX1000AllBUsMatterClosedValidationRules_dir

@gw.rules.RuleName("MCVXX1200 - Did Mediation Occur ")
internal class MCVXX1200DidMediationOccur {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.DidMediationOccurExt == null/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*/try{
    var strErrorReason="You cannot close this Legal Action ("+ matter.Name+ ") because Did Mediation Occur? is not answered. Please answer Did Mediation Occur? before closing the Legal Action."
    matter.reject("newloss", strErrorReason, Null, Null) 
  
} catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError(matter, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
