package rules.Segmentation.ExposureSegmentationRules_dir

@gw.rules.RuleName("ESG03000 - WC")
internal class ESG03000WC {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType =="WC"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* Run child rules *//*end00rule*/
  }
}
