package rules.Segmentation.ExposureSegmentationRules_dir

@gw.rules.RuleName("ESG02000 - Property")
internal class ESG02000Property {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.Claim.LossType =="PR"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//* Run child rules *//*end00rule*/
  }
}
