package rules.Preupdate.ClaimPreupdate_dir.CPUPL1000PLDClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUPL1100 - Set Medicare Flag")
internal class CPUPL1100SetMedicareFlag {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for (exp in claim.Exposures){
  exp.MedicareExposureExt = exp.isMedicareFeature(exp)
}
/*end00rule*/
  }
}
