<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" name="HPEmpowerService" targetNamespace="http://hp.services.gaic.com/" xmlns:ns0="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ns2="http://schemas.xmlsoap.org/wsdl/jms/" xmlns:ns3="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://hp.services.gaic.com/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsp:UsingPolicy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsdl:Required="true" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
    <sp:SecurityHeader xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" MustManifestEncryption="true" MustPrepend="true"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="SecurityTokens">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:SiteMinderSSOSecurityToken</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:HTTPUsernamePassword</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext">
          <sp:TokenType>sp:X509v3</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:SiteMinderSSOSecurityToken</sp:TokenType>
        </sp:SecurityToken>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:HTTPUsernamePassword</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:SiteMinderSSOSecurityToken</sp:TokenType>
        </sp:SecurityToken>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext">
          <sp:TokenType>sp:X509v3</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:HTTPUsernamePassword</sp:TokenType>
        </sp:SecurityToken>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext">
          <sp:TokenType>sp:X509v3</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
      <wsp:All>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:SiteMinderSSOSecurityToken</sp:TokenType>
        </sp:SecurityToken>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:_ns1="http://www.actional.com">
          <sp:TokenType>_ns1:HTTPUsernamePassword</sp:TokenType>
        </sp:SecurityToken>
        <sp:SecurityToken xmlns:sp="http://schemas.xmlsoap.org/ws/2002/12/secext">
          <sp:TokenType>sp:X509v3</sp:TokenType>
        </sp:SecurityToken>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="getVersion_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="refreshCprProperties_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="changeLogLevel_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="ping_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="checkDependencies_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="cancelEmpowerTransaction_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="getAvailableTemplates_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="createExstreamDocument_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="finalizeEmpowerDocument_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="createEmpowerDocument_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="removeEmpowerDocument_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" wsu:Id="getEmpowerDocumentUrl_input_policy">
    <wsp:PolicyReference URI="#SecurityTokens"/>
  </wsp:Policy>
  <types>
    <xsd:schema>
      <xsd:import namespace="http://hp.services.gaic.com/" schemaLocation="file:HPEmpowerService.wsdl.resources/wsdlfile.asvc.xsd"/>
    </xsd:schema>
  </types>
  <message name="HPEmpowerValidationException">
    <part element="tns:HPEmpowerValidationException" name="fault"/>
  </message>
  <message name="cancelEmpowerTransaction">
    <part element="tns:cancelEmpowerTransaction" name="parameters"/>
  </message>
  <message name="refreshCprProperties">
    <part element="tns:refreshCprProperties" name="parameters"/>
  </message>
  <message name="createEmpowerDocument">
    <part element="tns:createEmpowerDocument" name="parameters"/>
  </message>
  <message name="finalizeEmpowerDocument">
    <part element="tns:finalizeEmpowerDocument" name="parameters"/>
  </message>
  <message name="changeLogLevel">
    <part element="tns:changeLogLevel" name="parameters"/>
  </message>
  <message name="getEmpowerDocumentUrl">
    <part element="tns:getEmpowerDocumentUrl" name="parameters"/>
  </message>
  <message name="removeEmpowerDocumentResponse">
    <part element="tns:removeEmpowerDocumentResponse" name="parameters"/>
  </message>
  <message name="getAvailableTemplates">
    <part element="tns:getAvailableTemplates" name="parameters"/>
  </message>
  <message name="finalizeEmpowerDocumentResponse">
    <part element="tns:finalizeEmpowerDocumentResponse" name="parameters"/>
  </message>
  <message name="checkDependencies">
    <part element="tns:checkDependencies" name="parameters"/>
  </message>
  <message name="getVersionResponse">
    <part element="tns:getVersionResponse" name="parameters"/>
  </message>
  <message name="ping">
    <part element="tns:ping" name="parameters"/>
  </message>
  <message name="changeLogLevelResponse">
    <part element="tns:changeLogLevelResponse" name="parameters"/>
  </message>
  <message name="createExstreamDocument">
    <part element="tns:createExstreamDocument" name="parameters"/>
  </message>
  <message name="getAvailableTemplatesResponse">
    <part element="tns:getAvailableTemplatesResponse" name="parameters"/>
  </message>
  <message name="pingResponse">
    <part element="tns:pingResponse" name="parameters"/>
  </message>
  <message name="refreshCprPropertiesResponse">
    <part element="tns:refreshCprPropertiesResponse" name="parameters"/>
  </message>
  <message name="checkDependenciesResponse">
    <part element="tns:checkDependenciesResponse" name="parameters"/>
  </message>
  <message name="createEmpowerDocumentResponse">
    <part element="tns:createEmpowerDocumentResponse" name="parameters"/>
  </message>
  <message name="removeEmpowerDocument">
    <part element="tns:removeEmpowerDocument" name="parameters"/>
  </message>
  <message name="HPEmpowerException">
    <part element="tns:HPEmpowerException" name="fault"/>
  </message>
  <message name="Exception">
    <part element="tns:Exception" name="fault"/>
  </message>
  <message name="cancelEmpowerTransactionResponse">
    <part element="tns:cancelEmpowerTransactionResponse" name="parameters"/>
  </message>
  <message name="getEmpowerDocumentUrlResponse">
    <part element="tns:getEmpowerDocumentUrlResponse" name="parameters"/>
  </message>
  <message name="createExstreamDocumentResponse">
    <part element="tns:createExstreamDocumentResponse" name="parameters"/>
  </message>
  <message name="CommonUtilException">
    <part element="tns:CommonUtilException" name="fault"/>
  </message>
  <message name="getVersion">
    <part element="tns:getVersion" name="parameters"/>
  </message>
  <portType name="HPEmpowerService">
    <operation name="getEmpowerDocumentUrl">
      <input message="tns:getEmpowerDocumentUrl" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getEmpowerDocumentUrlRequest"/>
      <output message="tns:getEmpowerDocumentUrlResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getEmpowerDocumentUrlResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getEmpowerDocumentUrl/Fault/HPEmpowerException"/>
      <fault message="tns:Exception" name="Exception" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getEmpowerDocumentUrl/Fault/Exception"/>
    </operation>
    <operation name="removeEmpowerDocument">
      <input message="tns:removeEmpowerDocument" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/removeEmpowerDocumentRequest"/>
      <output message="tns:removeEmpowerDocumentResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/removeEmpowerDocumentResponse"/>
      <fault message="tns:Exception" name="Exception" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/removeEmpowerDocument/Fault/Exception"/>
    </operation>
    <operation name="createEmpowerDocument">
      <input message="tns:createEmpowerDocument" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createEmpowerDocumentRequest"/>
      <output message="tns:createEmpowerDocumentResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createEmpowerDocumentResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createEmpowerDocument/Fault/HPEmpowerException"/>
      <fault message="tns:HPEmpowerValidationException" name="HPEmpowerValidationException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createEmpowerDocument/Fault/HPEmpowerValidationException"/>
    </operation>
    <operation name="finalizeEmpowerDocument">
      <input message="tns:finalizeEmpowerDocument" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/finalizeEmpowerDocumentRequest"/>
      <output message="tns:finalizeEmpowerDocumentResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/finalizeEmpowerDocumentResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/finalizeEmpowerDocument/Fault/HPEmpowerException"/>
      <fault message="tns:HPEmpowerValidationException" name="HPEmpowerValidationException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/finalizeEmpowerDocument/Fault/HPEmpowerValidationException"/>
    </operation>
    <operation name="createExstreamDocument">
      <input message="tns:createExstreamDocument" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createExstreamDocumentRequest"/>
      <output message="tns:createExstreamDocumentResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createExstreamDocumentResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createExstreamDocument/Fault/HPEmpowerException"/>
      <fault message="tns:HPEmpowerValidationException" name="HPEmpowerValidationException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/createExstreamDocument/Fault/HPEmpowerValidationException"/>
    </operation>
    <operation name="getAvailableTemplates">
      <input message="tns:getAvailableTemplates" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getAvailableTemplatesRequest"/>
      <output message="tns:getAvailableTemplatesResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getAvailableTemplatesResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getAvailableTemplates/Fault/HPEmpowerException"/>
      <fault message="tns:HPEmpowerValidationException" name="HPEmpowerValidationException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getAvailableTemplates/Fault/HPEmpowerValidationException"/>
    </operation>
    <operation name="cancelEmpowerTransaction">
      <input message="tns:cancelEmpowerTransaction" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/cancelEmpowerTransactionRequest"/>
      <output message="tns:cancelEmpowerTransactionResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/cancelEmpowerTransactionResponse"/>
      <fault message="tns:HPEmpowerException" name="HPEmpowerException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/cancelEmpowerTransaction/Fault/HPEmpowerException"/>
      <fault message="tns:HPEmpowerValidationException" name="HPEmpowerValidationException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/cancelEmpowerTransaction/Fault/HPEmpowerValidationException"/>
    </operation>
    <operation name="checkDependencies">
      <input message="tns:checkDependencies" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/checkDependenciesRequest"/>
      <output message="tns:checkDependenciesResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/checkDependenciesResponse"/>
      <fault message="tns:CommonUtilException" name="CommonUtilException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/checkDependencies/Fault/CommonUtilException"/>
    </operation>
    <operation name="ping">
      <input message="tns:ping" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/pingRequest"/>
      <output message="tns:pingResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/pingResponse"/>
    </operation>
    <operation name="changeLogLevel">
      <input message="tns:changeLogLevel" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/changeLogLevelRequest"/>
      <output message="tns:changeLogLevelResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/changeLogLevelResponse"/>
      <fault message="tns:CommonUtilException" name="CommonUtilException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/changeLogLevel/Fault/CommonUtilException"/>
    </operation>
    <operation name="refreshCprProperties">
      <input message="tns:refreshCprProperties" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/refreshCprPropertiesRequest"/>
      <output message="tns:refreshCprPropertiesResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/refreshCprPropertiesResponse"/>
      <fault message="tns:CommonUtilException" name="CommonUtilException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/refreshCprProperties/Fault/CommonUtilException"/>
    </operation>
    <operation name="getVersion">
      <input message="tns:getVersion" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getVersionRequest"/>
      <output message="tns:getVersionResponse" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getVersionResponse"/>
      <fault message="tns:CommonUtilException" name="CommonUtilException" wsam:Action="http://hp.services.gaic.com/HPEmpowerService/getVersion/Fault/CommonUtilException"/>
    </operation>
  </portType>
  <binding name="HPEmpowerServicePortBinding" type="tns:HPEmpowerService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getEmpowerDocumentUrl">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#getEmpowerDocumentUrl_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="Exception">
        <soap:fault name="Exception" use="literal"/>
      </fault>
    </operation>
    <operation name="removeEmpowerDocument">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#removeEmpowerDocument_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="Exception">
        <soap:fault name="Exception" use="literal"/>
      </fault>
    </operation>
    <operation name="createEmpowerDocument">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#createEmpowerDocument_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="HPEmpowerValidationException">
        <soap:fault name="HPEmpowerValidationException" use="literal"/>
      </fault>
    </operation>
    <operation name="finalizeEmpowerDocument">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#finalizeEmpowerDocument_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="HPEmpowerValidationException">
        <soap:fault name="HPEmpowerValidationException" use="literal"/>
      </fault>
    </operation>
    <operation name="createExstreamDocument">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#createExstreamDocument_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="HPEmpowerValidationException">
        <soap:fault name="HPEmpowerValidationException" use="literal"/>
      </fault>
    </operation>
    <operation name="getAvailableTemplates">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#getAvailableTemplates_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="HPEmpowerValidationException">
        <soap:fault name="HPEmpowerValidationException" use="literal"/>
      </fault>
    </operation>
    <operation name="cancelEmpowerTransaction">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#cancelEmpowerTransaction_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="HPEmpowerException">
        <soap:fault name="HPEmpowerException" use="literal"/>
      </fault>
      <fault name="HPEmpowerValidationException">
        <soap:fault name="HPEmpowerValidationException" use="literal"/>
      </fault>
    </operation>
    <operation name="checkDependencies">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#checkDependencies_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="CommonUtilException">
        <soap:fault name="CommonUtilException" use="literal"/>
      </fault>
    </operation>
    <operation name="ping">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#ping_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="changeLogLevel">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#changeLogLevel_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="CommonUtilException">
        <soap:fault name="CommonUtilException" use="literal"/>
      </fault>
    </operation>
    <operation name="refreshCprProperties">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#refreshCprProperties_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="CommonUtilException">
        <soap:fault name="CommonUtilException" use="literal"/>
      </fault>
    </operation>
    <operation name="getVersion">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#getVersion_input_policy"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="CommonUtilException">
        <soap:fault name="CommonUtilException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="HPEmpowerService">
    <port binding="tns:HPEmpowerServicePortBinding" name="HPEmpowerServicePort">
      <soap:address location="https://sstdev.td.afg:1024/sst/hp.empower_1"/>
    </port>
  </service>
</definitions>