package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1292-Beneficiary Related and Dependency code")
internal class CVWC1292BeneficiaryRelatedandDependencycode {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*///Added new rule to ensure the Beneficiay Dependency code and Beneficiary Relationship code
//are not Null at Ability to pay validation level
//Developer:Asaikumar Date:05/06/2015

true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/libraries.Claim_Entity.ClaimRelatedContactFunctions.BeneficiaryDepnd(claim)
libraries.Claim_Entity.ClaimRelatedContactFunctions.BeneficiaryRelatn(claim)



/*end00rule*/
  }
}
