package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1225 - Date Of Birth")
internal class CVWC1225DateOfBirth {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.DateOfBirth==null
/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "claimant.DateOfBirth", "payment", displaykey.Rules.Validation.Claim.WorkersComp.DateOfBirthATP, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
