package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1240 - Type Of Loss")
internal class CVWC1240TypeOfLoss {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.TypeOfLossMostExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "TypeOfLossMostExt", "payment", displaykey.Rules.Validation.Claim.WorkersComp.TypeOfLoss, null, null )/*end00rule*/
  }
}
