package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1250 - Employment Status")
internal class CVWC1250EmploymentStatus {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.EmploymentData.EmploymentStatus == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "EmploymentData.EmploymentStatus", "payment", displaykey.Rules.Validation.Claim.WorkersComp.EmploymentStatus, null, null )/*end00rule*/
  }
}
