package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1260 - Jurisdiction Case Number")
internal class CVWC1260JurisdictionCaseNumber {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.JurisClaimNumberExt == null and 
claim.JurisdictionState == typekey.State.TC_NY
//10.21.15 - cmullin - disabled rule based on updated requirements/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "JurisClaimNumberExt", "payment", displaykey.Rules.Validation.Claim.WorkersComp.JurisdictionCase, null, null )/*end00rule*/
  }
}
