package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1270 - Marital Status")
internal class CVWC1270MaritalStatus {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.MaritalStatus == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try{
  claim.rejectField( "claimant.MaritalStatus", "payment", displaykey.Rules.Validation.Claim.WorkersComp.MaritalStatus, null, null) //.rejectField( "claimant.MaritalStatus", "payment", displaykey.Rules.Validation.Claim.WorkersComp.MaritalStatus, null, null )
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}
/*end00rule*/
  }
}
