package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1280 - Date Of Hire")
internal class CVWC1280DateOfHire {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.EmploymentData.HireDate == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "EmploymentData.HireDate", "payment", displaykey.Rules.Validation.Claim.WorkersComp.DateOfHire, null, null )/*end00rule*/
  }
}
