package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1210 - Jurisdiction State")
internal class CVWC1210JurisdictionState {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.JurisdictionState == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "JurisdictionState", "payment", displaykey.Rules.Validation.Claim.WorkersComp.JurisdictionState, null, null )/*end00rule*/
  }
}
