package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1215 - Occupation")
internal class CVWC1215Occupation {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.Occupation == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "claimant.Occupation", "payment", displaykey.Rules.Validation.Claim.WorkersComp.Occupation, null, null )/*end00rule*/
  }
}
