package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1294 - SSN")
internal class CVWC1294SSN {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.TaxID == null && 
claim.InjuredWorker.UndocumentedWorkerExt != true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try {
 claim.rejectField( "claimant.TaxID", "payment", displaykey.Rules.Validation.Claim.WorkersComp.SSN, null, null )
}catch(e) {
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
