package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1255 - Compensability Controverted")
internal class CVWC1255CompensabilityControverted {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ControvertedExt == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "ControvertedExt", "payment", displaykey.Rules.Validation.Claim.WorkersComp.Compensability, null, null )/*end00rule*/
  }
}
