package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1230 - Injured Worker First Name")
internal class CVWC1230InjuredWorkerFirstName {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.FirstName == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectSubField( claim.claimant, "FirstName", "payment", displaykey.Rules.Validation.Claim.WorkersComp.InjWorkerFirstName, null, null )/*end00rule*/
  }
}
