package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVWC1290 - Date Employer Notified")
internal class CVWC1290DateEmployerNotified {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.DateRptdToEmployer == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "DateRptdToEmployer", "payment", displaykey.Rules.Validation.Claim.WorkersComp.DateEmployerNotified, null, null )/*end00rule*/
  }
}
