package rules.Validation.ClaimValidationRules_dir.CVAG1000AgribusinessClaimValidationRules_dir.CVAG1200ValidationattheAbilitytoPayLevel_dir

@gw.rules.RuleName("CVAG1210 - Weather Related Required")
internal class CVAG1210WeatherRelatedRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == LossType.TC_AGRIAUTO or
claim.LossType == LossType.TC_AGRIPROPERTY
/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/If (claim.WeatherRelated_Ext ==Null) 
   {
     claim.reject( "payment", displaykey.Rules.Validation.ClaimWeatherRelated.Blank, null, null )
   }
 /*end00rule*/
  }
}
