package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVAG1000AgriBusinessPolicyValidationRules_dir

@gw.rules.RuleName("PVAG1300 - Ability to Pay")
internal class PVAG1300AbilitytoPay {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/True/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
