package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVAG1000AgriBusinessPolicyValidationRules_dir

@gw.rules.RuleName("PVAG1200 - Valid for ISO")
internal class PVAG1200ValidforISO {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
