package rules.Preupdate.ExposurePreupdate_dir.EPUAG1000AgriBusinessExposurePreUpdateRules_dir

@gw.rules.RuleName("EPUAG1500 - RULES THAT CREATE ACTIVITIES")
internal class EPUAG1500RULESTHATCREATEACTIVITIES {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
