package rules.Assignment.GlobalClaimAssignmentRules_dir

@gw.rules.RuleName("GCAAG100 - AgriBusiness Global Claim Assignment Rules")
internal class GCAAG100AgriBusinessGlobalClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules specific to AgriBusiness Line of Business*//*end00rule*/
  }
}
