package rules.Assignment.GlobalClaimAssignmentRules_dir

@gw.rules.RuleName("GCAFC100 - FidCrime Global Claim Assignment Rules")
internal class GCAFC100FidCrimeGlobalClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules specific to FidCrime Line of Business*//*end00rule*/
  }
}
