package rules.Assignment.GlobalClaimAssignmentRules_dir

@gw.rules.RuleName("GCAIM100 - PIM Global Claim Assignment Rules")
internal class GCAIM100PIMGlobalClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "PIMINMARINE"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules specific to P&IM Line of Business*//*end00rule*/
  }
}
