package rules.Assignment.GlobalClaimAssignmentRules_dir

@gw.rules.RuleName("GCAXX100 - All BUs Global Claim Assignment Rules")
internal class GCAXX100AllBUsGlobalClaimAssignmentRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*Create child rules common across all Lines of Business*//*end00rule*/
  }
}
