package rules.Reopened.ExposureReopened_dir.ERXX1000AllBUExposureReopenedRules_dir

@gw.rules.RuleName("ERXX1100 - Notify external systems")
internal class ERXX1100Notifyexternalsystems {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true /* always notify *//*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.Claim.addEvent(  "exposure_reopened" )/*end00rule*/
  }
}
