package rules.Validation.ClaimValidationRules_dir.CVIM1000PIMClaimValidationRules_dir.CVIM1300ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVIM1310 - Detail Loss Cause is Required")
internal class CVIM1310DetailLossCauseisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*///02-22-2011 Travis Newcomb, Defect 3901: PIM - Detail Loss Cause Needs 
//  to be Required for ATP
claim.ex_DetailLossCause==null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "ex_DetailLossCause", "payment", displaykey.Rules.Validation.Claim.PIM.DetailLossCause, null, null )/*end00rule*/
  }
}
