package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1200AbilitytoPay_dir.PVXX1210AgencyRequirements_dir

@gw.rules.RuleName("PVXX1211 - Agency needed on Policy")
internal class PVXX1211AgencyneededonPolicy {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.ex_Agency.Name == null
//10.29.15 - cmullin - Defect 7750 - Producer information moved from ATP to New Loss Policy Validation (Enterprise). Rule disabled./*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "ex_Agency", "payment", "Agency Name and Address Information is necessary", null, null )
/*end00rule*/
  }
}
