package rules.Preupdate.MatterPreupdate_dir.MPUXX1000AllBUsPreUpdateRules_dir

@gw.rules.RuleName("MPUXX1100 - Manage Roles")
internal class MPUXX1100ManageRoles {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/!matter.New/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
