package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX1110PolicyDatesRequirements_dir

@gw.rules.RuleName("PVXX1111 - Policy Effective/Expiration Dates Required")
internal class PVXX1111PolicyEffectiveExpirationDatesRequired {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/!policy.Verified and 
(policy.EffectiveDate == null || policy.ExpirationDate == null)/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.reject( "newloss",displaykey.Rules.Validation.Policy.Enterprise.NewLoss.EffectiveDate, null, null )
gw.api.util.Logger.logInfo( actions.getRule().DisplayName )

/*end00rule*/
  }
}
