package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVXX1000AllBUsPolicyValidationRules_dir.PVXX1100NewLossLevel_dir.PVXX1110PolicyDatesRequirements_dir

@gw.rules.RuleName("PVXX1112 - Policy Effective/Original Effective Date")
internal class PVXX1112PolicyEffectiveOriginalEffectiveDate {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.OrigEffectiveDate != null && policy.EffectiveDate != null &&
    gw.api.util.DateUtil.compareIgnoreTime(policy.OrigEffectiveDate,policy.EffectiveDate)>0/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*/policy.rejectField( "EffectiveDate",
                                    "newloss",
                                    "Policy effective date must not be later than the policy original effective date.",
                                    null,
                                    null )/*end00rule*/
  }
}
