package rules.Validation.MatterClosedValidationRules_dir

@gw.rules.RuleName("MCVAG1000 - AgriBusiness Matter Closed Validation Rules")
internal class MCVAG1000AgriBusinessMatterClosedValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType == "AGRIAUTO" ||
matter.Claim.LossType == "AGRILIABILITY" ||
matter.Claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
