package rules.Validation.MatterClosedValidationRules_dir

@gw.rules.RuleName("MCVEQ1000 - Equine Matter Closed Validation Rules")
internal class MCVEQ1000EquineMatterClosedValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
