package rules.Validation.MatterClosedValidationRules_dir

@gw.rules.RuleName("MCVXX1000 - All BUs Matter Closed Validation Rules")
internal class MCVXX1000AllBUsMatterClosedValidationRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
