package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1200ValidationattheISOLevel_dir.CVXX1220General_dir

@gw.rules.RuleName("CVXX1223 - Loss Location State is Required")
internal class CVXX1223LossLocationStateisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossLocation==null ||
(claim.LossLocation.Country=="US" and claim.LossLocation.State==null)/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "iso", "A Loss Location state is required for ISO Validation", null, null )/*end00rule*/
  }
}
