package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1200ValidationattheISOLevel_dir.CVXX1220General_dir

@gw.rules.RuleName("CVXX1222 - Loss Description is Required")
internal class CVXX1222LossDescriptionisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.Description==Null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "Description", "iso", "Please provide the loss description for the Claim.", Null, Null )/*end00rule*/
  }
}
