package rules.Validation.ClaimValidationRules_dir.CVXX1000AllBusinessUnitClaimValidationRules_dir.CVXX1200ValidationattheISOLevel_dir.CVXX1220General_dir

@gw.rules.RuleName("CVXX1224 - Claim must be Assigned")
internal class CVXX1224ClaimmustbeAssigned {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.AssignmentStatus!="assigned" and
(claim.OriginalVersion as Claim).IncidentReport==claim.IncidentReport/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.reject( "iso", "There must be an assigned adjuster to be valid for ISO.", null, null )/*end00rule*/
  }
}
