package rules.Validation.ExposureReopenedValidationRules_dir.ERVXX1000AllBUExposureReopenValidationRules_dir

@gw.rules.RuleName("ERVXX1200 - Check for active assigned user")
internal class ERVXX1200Checkforactiveassigneduser {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*//*Defect 1819 - To prevent activities, etc from being assigned to Default Owner
Author: erawe
Date: 5/15/09
Updates:
*/
!exposure.AssignedUser.Credential.Active
/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/try{
  exposure.reject( "newloss", "Current assigned user is not active, please assign the feature to an active user before reopening.", null, null )
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( exposure, actions.getRule().DisplayName, e, null );
}/*end00rule*/
  }
}
