package rules.Validation.ExposureReopenedValidationRules_dir.ERVXX1000AllBUExposureReopenValidationRules_dir

@gw.rules.RuleName("ERVXX1100 - Claim is Still Closed")
internal class ERVXX1100ClaimisStillClosed {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.State<>"open"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.reject( "newloss", "You can only reopen an exposure for an open claim.", null, null )/*end00rule*/
  }
}
