package rules.Postsetup.MatterPostsetup_dir

@gw.rules.RuleName("MPOEQ1000 - Equine Matter PostSetup Rules")
internal class MPOEQ1000EquineMatterPostSetupRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
