package rules.Postsetup.MatterPostsetup_dir

@gw.rules.RuleName("MPOIM1000 - PIM Matter PostSetup Rules")
internal class MPOIM1000PIMMatterPostSetupRules {
  static function doCondition(matter : entity.Matter) : boolean {
    return /*start00rule*/matter.Claim.LossType=="PIMINMARINE"/*end00rule*/
  }

  static function doAction(matter : entity.Matter, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
