package rules.Archive.DefaultGroupClaimArchivingRules_dir

@gw.rules.RuleName("ARC01000 - Claim State Rule")
internal class ARC01000ClaimStateRule {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/!claim.Closed/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.skipFromArchiving(displaykey.Rules.Archive.ClaimState.Closed)/*end00rule*/
  }
}
