package rules.Validation.ActivityValidationRules_dir

@gw.rules.RuleName("AVAG1000 - AgriBusiness Activity Validation Rules")
internal class AVAG1000AgriBusinessActivityValidationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType == "AGRIAUTO" ||
activity.Claim.LossType == "AGRILIABILITY" ||
activity.Claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
