package rules.Validation.ActivityValidationRules_dir

@gw.rules.RuleName("AVEQ1000 - Equine Activity Validation Rules")
internal class AVEQ1000EquineActivityValidationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
