package rules.Validation.ActivityValidationRules_dir

@gw.rules.RuleName("AVWC1000 - Workers' Comp Activity Validation Rules")
internal class AVWC1000WorkersCompActivityValidationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(activity.Claim)/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
