package rules.Validation.ActivityValidationRules_dir

@gw.rules.RuleName("AVXX1000 - All BUs Activity Validation Rules")
internal class AVXX1000AllBUsActivityValidationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
