package rules.Closed.ActivityClosed_dir

@gw.rules.RuleName("ACEN1000 - Environmental Activity Closed Rules")
internal class ACEN1000EnvironmentalActivityClosedRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType=="ENVLIAB"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
