package rules.Closed.ActivityClosed_dir

@gw.rules.RuleName("ACEQ1000 - Equine Activity Closed Rules")
internal class ACEQ1000EquineActivityClosedRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
