package rules.Closed.ActivityClosed_dir

@gw.rules.RuleName("ACXX1000 - All BUs Activity Closed Rules")
internal class ACXX1000AllBUsActivityClosedRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*///* Run child rules/*end00rule*/
  }
}
