package rules.Exception.ActivityEscalationRules_dir.AEXX1000AExclusionfilters_dir

@gw.rules.RuleName("AEIM1000 - PIM Activity Escalation Rules")
internal class AEIM1000PIMActivityEscalationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
