package rules.Exception.ActivityEscalationRules_dir.AEXX1000AExclusionfilters_dir

@gw.rules.RuleName("AEXX1000 - All BU Activity Escalation Rules")
internal class AEXX1000AllBUActivityEscalationRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/!util.user.GroupsHelper.isClaimManager(activity.AssignedUser)
/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
