package rules.Validation.ClaimValidationRules_dir.CVEQ1000EquineClaimValidationRules_dir.CVEQ1200ValidationatAbilitytoPayLevel_dir

@gw.rules.RuleName("CVEQ1210 - Detail Loss Cause is Required")
internal class CVEQ1210DetailLossCauseisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.ex_DetailLossCause==Null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "ex_DetailLossCause", "payment", displaykey.Rules.Validation.Claim.Equine.DetailLossCause, Null, Null )

  /*end00rule*/
  }
}
