package rules.Loaded.ClaimLoaded_dir

@gw.rules.RuleName("CLAG1000 - AgriBusiness Claim Loaded Rules")
internal class CLAG1000AgriBusinessClaimLoadedRules {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.LossType == "AGRIAUTO" ||
claim.LossType == "AGRILIABILITY" ||
claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
