package rules.Validation.ClaimClosedValidationRules_dir.CCVFC1000FidCrimeClaimClosedValidationRules_dir

@gw.rules.RuleName("CCVFC1100 - Validate Exposure Details KR")
internal class CCVFC1100ValidateExposureDetailsKR {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/!claim.Exposures.IsEmpty/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for(exp in claim.Exposures){
  try{ 
    if(exp.ExposureType == ExposureType.TC_KR_KIDNAPRANSOM && exp.ExposureDetailsExt==null){
      claim.rejectSubField(exp,"ExposureDetailsExt","newloss", "On " + "(" + exp.ClaimOrder + ")" + " " + exp.ExposureType.DisplayName + ": " +  displaykey.Rules.Validation.Claim.KR.ExpsoureDetail, null,null)
    }
  }
  catch(e)
  {
    util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
  }
}/*end00rule*/
  }
}
