package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EWEQ1000 - Equine Exposure Workplan Rules")
internal class EWEQ1000EquineExposureWorkplanRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
