package rules.Workplan.ExposureWorkplan_dir

@gw.rules.RuleName("EWXX1000 - All BUs Exposure Workplan Rules")
internal class EWXX1000AllBUsExposureWorkplanRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
