package rules.Validation.ClaimValidationRules_dir.CVEQ1000EquineClaimValidationRules_dir

@gw.rules.RuleName("CVEQ1200 - Validation at Ability to Pay Level")
internal class CVEQ1200ValidationatAbilitytoPayLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
