package rules.Validation.ClaimValidationRules_dir.CVEQ1000EquineClaimValidationRules_dir

@gw.rules.RuleName("CVEQ1100 - Validation at New Loss Level")
internal class CVEQ1100ValidationatNewLossLevel {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
