package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05730OffRoadVehicle_dir

@gw.rules.RuleName("EXV05731 - Serial Number Present")
internal class EXV05731SerialNumberPresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.LossParty != "third_party" 
and exposure.VehicleIncident.Vehicle.SerialNumber == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.VehicleSerialNumRequired, null, null);/*end00rule*/
  }
}
