package rules.Validation.ExposureValidationRules_dir.EXV05000ISOValidation_dir.EXV05700VehicleExposure_dir.EXV05730OffRoadVehicle_dir

@gw.rules.RuleName("EXV05732 - Off Road Type Present")
internal class EXV05732OffRoadTypePresent {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/Exposure.VehicleIncident.Vehicle.OffRoadStyle == null/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*/Exposure.rejectField("VehicleIncident.Vehicle", "iso", displaykey.Rules.Validation.Exposure.VehicleOffRoadStyleRequired, null, null);/*end00rule*/
  }
}
