package rules.Preupdate.PolicyPreupdate_dir.PPUXXPRERulesthatneedtorun_dir.PPUPIMPimPolicyPreUPdateRules_dir

@gw.rules.RuleName("PPUPIM1100 - Filter Package Policy Data per Loss Type")
internal class PPUPIM1100FilterPackagePolicyDataperLossType {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Verified==true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
