package rules.Reopened.ClaimReopened_dir

@gw.rules.RuleName("CRO01000 - Notify external systems")
internal class CRO01000Notifyexternalsystems {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true /* Always notify *//*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/Claim.addEvent( "claim_reopened")/*end00rule*/
  }
}
