package rules.Exception.ClaimExceptionRules_dir.CEXX1000AExclusionfilters_dir.CEXX1000AllBUClaimExceptionRules_dir

@gw.rules.RuleName("CEXX1400 - Bulk Recoveries")
internal class CEXX1400BulkRecoveries {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*//*Bulk Recovery Rules*/

true/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
