package rules.Preupdate.ClaimPreupdate_dir.CPUEL1000ELDClaimPreUpdateRules_dir

@gw.rules.RuleName("CPUEL1700 - Set Medicare Flag")
internal class CPUEL1700SetMedicareFlag {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/true

/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/for (exp in claim.Exposures){
  exp.MedicareExposureExt = exp.IsMedicareExposureExt 
}
/*end00rule*/
  }
}
