package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVEQ1000EquinePolicyValidationRules_dir

@gw.rules.RuleName("PVEQ1200 - ISO Validation Level")
internal class PVEQ1200ISOValidationLevel {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/policy.Claim.ISOEnabled==true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
