package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVEQ1000EquinePolicyValidationRules_dir

@gw.rules.RuleName("PVEQ1300 - Ability to Pay")
internal class PVEQ1300AbilitytoPay {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
