package rules.Validation.PolicyValidationRules_dir.PVNonVerifiedOnly_dir.PVEQ1000EquinePolicyValidationRules_dir

@gw.rules.RuleName("PVEQ1100 - New Loss Level")
internal class PVEQ1100NewLossLevel {
  static function doCondition(policy : entity.Policy) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
