package rules.Validation.ExposureReopenedValidationRules_dir

@gw.rules.RuleName("ERVAG1000 - Agribusiness Exposure Reopen Validation Rules")
internal class ERVAG1000AgribusinessExposureReopenValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType == "AGRIAUTO" ||
exposure.Claim.LossType == "AGRILIABILITY" ||
exposure.Claim.LossType == "AGRIPROPERTY"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
