package rules.Validation.ExposureReopenedValidationRules_dir

@gw.rules.RuleName("ERVEQ1000 - Equine Exposure Reopen Validation Rules")
internal class ERVEQ1000EquineExposureReopenValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
