package rules.Validation.ExposureReopenedValidationRules_dir

@gw.rules.RuleName("ERVXX1000 - All BU Exposure Reopen Validation Rules")
internal class ERVXX1000AllBUExposureReopenValidationRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
