package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUAC1000 - ACLs Activity PreUpdate Rules")
internal class APUAC1000ACLsActivityPreUpdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
