package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUBS1000 - Bonds Activity PreUpdate Rules")
internal class APUBS1000BondsActivityPreUpdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType == typekey.LossType.TC_COMMBONDS/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
