package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUEQ1000 - Equine Activity PreUpdate Rules")
internal class APUEQ1000EquineActivityPreUpdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
