package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUOM1000 - Ocean Marine Preupdate Rules")
internal class APUOM1000OceanMarinePreupdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/activity.Claim.LossType == typekey.LossType.TC_OMAVALON/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
