package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUWC1000 - Workers' Comp Activity PreUpdate Rules")
internal class APUWC1000WorkersCompActivityPreUpdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/util.WCHelper.isWCorELLossType(activity.Claim)/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
