package rules.Preupdate.ActivityPreupdate_dir

@gw.rules.RuleName("APUXX1000 - All BUs Activity PreUpdate Rules")
internal class APUXX1000AllBUsActivityPreUpdateRules {
  static function doCondition(activity : entity.Activity) : boolean {
    return /*start00rule*/true/*end00rule*/
  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
