package rules.Closed.ExposureClosed_dir

@gw.rules.RuleName("ECEQ1000 - Equine Exposure Closed Rules")
internal class ECEQ1000EquineExposureClosedRules {
  static function doCondition(exposure : entity.Exposure) : boolean {
    return /*start00rule*/exposure.Claim.LossType =="EQUINE"/*end00rule*/
  }

  static function doAction(exposure : entity.Exposure, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
