package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1300ValidationatISOLevel_dir

@gw.rules.RuleName("CVWC1330 - Injured Worker First Name")
internal class CVWC1330InjuredWorkerFirstName {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.FirstName == null/*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/try{
  claim.rejectField( "claimant.FirstName", "iso", displaykey.Rules.Validation.Claim.WorkersComp.InjWorkerFirstName, null, null )
}catch(e){
  util.ErrorHandling.GAICErrorHandling.logError( claim, actions.getRule().DisplayName, e, null )
}/*end00rule*/
  }
}
