package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1300ValidationatISOLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1320 - Date of Birth")
internal class CVWC1320DateofBirth {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.DateOfBirth == null
//11.2.15 - cmullin - DOB moved back to ATP. Rule disabled./*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "claimant.DateOfBirth", "iso", displaykey.Rules.Validation.Claim.WorkersComp.DateOfBirth, null, null )/*end00rule*/
  }
}
