package rules.Validation.ClaimValidationRules_dir.CVWC1000WorkersCompClaimValidationRules_dir.CVWC1300ValidationatISOLevel_dir

@gw.rules.RuleDisabled
@gw.rules.RuleName("CVWC1310 - SSN is Required")
internal class CVWC1310SSNisRequired {
  static function doCondition(claim : entity.Claim) : boolean {
    return /*start00rule*/claim.claimant.TaxID == null && 
claim.InjuredWorker.UndocumentedWorkerExt != true
// 10.26.15 - cmullin - SSN is only required for ATP. Disabled rule./*end00rule*/
  }

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/claim.rejectField( "claimant.TaxID", "iso", displaykey.Rules.Validation.Claim.WorkersComp.SSN, null, null )/*end00rule*/
  }
}
